-- Minimal, sanitized staging-like catalog for DB.0D dry-run.
-- Run only in a disposable local database created for this harness.
-- It contains no production rows, identifiers, tokens, hashes or payloads.

DROP SCHEMA IF EXISTS public CASCADE;
DROP SCHEMA IF EXISTS auth CASCADE;
DROP SCHEMA IF EXISTS extensions CASCADE;

CREATE SCHEMA public AUTHORIZATION postgres;
CREATE SCHEMA auth AUTHORIZATION postgres;
CREATE SCHEMA extensions AUTHORIZATION postgres;

GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;

CREATE TABLE auth.users (
    id uuid PRIMARY KEY,
    email text,
    raw_user_meta_data jsonb
);

CREATE VIEW public.users AS
SELECT
    source.id,
    source.email,
    COALESCE(
        NULLIF(source.raw_user_meta_data ->> 'full_name', ''),
        NULLIF(source.raw_user_meta_data ->> 'name', ''),
        source.email
    ) AS name
FROM auth.users AS source;

GRANT SELECT ON public.users TO authenticated, service_role;

CREATE FUNCTION public.tanda1_user_is_member(p_tenant_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO public
AS $function$
    SELECT p_tenant_id IS NOT NULL;
$function$;

CREATE FUNCTION public.tanda1_user_has_role(p_tenant_id uuid, p_roles text[])
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO public
AS $function$
    SELECT p_tenant_id IS NOT NULL AND cardinality(p_roles) > 0;
$function$;

CREATE FUNCTION public.tracking_hash_token(p_token text)
RETURNS text
LANGUAGE sql
IMMUTABLE
STRICT
AS $function$
    SELECT md5(p_token);
$function$;

CREATE FUNCTION public.tracking_validate_token(p_token text, p_required_scope text)
RETURNS TABLE (
    token_id uuid,
    tenant_id uuid,
    operation_id uuid,
    token_scope text,
    token_state text,
    expires_at timestamptz
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO public
AS $function$
    SELECT NULL::uuid, NULL::uuid, NULL::uuid, p_required_scope, 'active'::text, now()
    WHERE p_token IS NULL;
$function$;

CREATE FUNCTION public.rpc_get_public_tracking(p_token text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO public
AS $function$
BEGIN
    RETURN jsonb_build_object('status', CASE WHEN p_token IS NULL THEN 'not_found' ELSE 'success' END);
END;
$function$;

CREATE FUNCTION public.rpc_get_driver_view(p_token text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO public
AS $function$
BEGIN
    RETURN jsonb_build_object('status', CASE WHEN p_token IS NULL THEN 'not_found' ELSE 'success' END);
END;
$function$;

CREATE FUNCTION public.rpc_post_driver_event(
    p_token text,
    p_action text,
    p_source text,
    p_lat numeric,
    p_lng numeric,
    p_accuracy numeric,
    p_municipality text,
    p_state_name text,
    p_country_code character,
    p_incident_type text,
    p_incident_note text,
    p_client_timestamp timestamptz,
    p_offline_queued boolean
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO public
AS $function$
BEGIN
    RETURN jsonb_build_object(
        'accepted', p_token IS NOT NULL AND p_action IS NOT NULL,
        'source', p_source,
        'offline_queued', p_offline_queued
    );
END;
$function$;

REVOKE ALL ON FUNCTION public.tanda1_user_is_member(uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.tanda1_user_has_role(uuid, text[]) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.tanda1_user_is_member(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.tanda1_user_has_role(uuid, text[]) TO authenticated, service_role;

REVOKE ALL ON FUNCTION public.rpc_get_public_tracking(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.rpc_get_driver_view(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.rpc_post_driver_event(
    text, text, text, numeric, numeric, numeric, text, text, character,
    text, text, timestamp with time zone, boolean
) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rpc_get_public_tracking(text) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.rpc_get_driver_view(text) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.rpc_post_driver_event(
    text, text, text, numeric, numeric, numeric, text, text, character,
    text, text, timestamp with time zone, boolean
) TO anon, authenticated, service_role;

-- Representative class-D object that DB.0D must preserve untouched.
CREATE TABLE public.daily_work_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payload jsonb
);
