\set ON_ERROR_STOP on
BEGIN;

DO $contract$
DECLARE s text;o oid;t text;
BEGIN
 FOREACH t IN ARRAY ARRAY['claim_service_policies','service_claims','service_claim_events','service_claim_actions','service_claim_financials','service_claim_contacts'] LOOP
  IF to_regclass('public.'||t) IS NULL OR NOT EXISTS(SELECT 1 FROM pg_class WHERE oid=to_regclass('public.'||t) AND relrowsecurity) THEN RAISE EXCEPTION 'F10 table/RLS %',t;END IF;
  IF has_table_privilege('authenticated','public.'||t,'SELECT,INSERT,UPDATE,DELETE') OR has_table_privilege('anon','public.'||t,'SELECT') OR has_table_privilege('service_role','public.'||t,'SELECT') THEN RAISE EXCEPTION 'F10 direct ACL %',t;END IF;
 END LOOP;
 FOREACH s IN ARRAY ARRAY[
 'public.rpc_upsert_claim_service_policy(uuid,uuid,jsonb)','public.rpc_create_service_claim(uuid,jsonb)','public.rpc_create_service_claim_from_incident(uuid,jsonb)','public.rpc_get_claim_reference_data(uuid)','public.rpc_list_service_claims(uuid,jsonb)','public.rpc_get_service_claim(uuid)','public.rpc_transition_service_claim(uuid,text,text)','public.rpc_reopen_service_claim(uuid,text)','public.rpc_assign_service_claim(uuid,uuid)','public.rpc_update_claim_classification(uuid,text,text,text)','public.rpc_add_claim_note(uuid,text)','public.rpc_log_claim_contact(uuid,text,uuid,text,text,timestamptz)','public.rpc_upsert_claim_action(uuid,uuid,jsonb)','public.rpc_update_claim_action_status(uuid,text,text)','public.rpc_upsert_claim_financial(uuid,uuid,jsonb)','public.rpc_record_claim_settlement(uuid,jsonb)','public.rpc_get_claim_finance_handoff(uuid)','public.rpc_register_claim_document(uuid,jsonb)','public.rpc_relate_claim_document(uuid,uuid,text)','public.rpc_list_claim_documents(uuid)','public.rpc_list_partner_claims(text,uuid,integer)','public.rpc_get_claims_dashboard(uuid,timestamptz,timestamptz)','public.rpc_list_claim_attention_items(uuid)','public.rpc_search_claims(uuid,text,integer)','public.rpc_get_claim_reporting(uuid,timestamptz,timestamptz)','public.rpc_export_claims(uuid,jsonb)','public.rpc_list_claim_saved_views(uuid)','public.rpc_save_claim_view(uuid,uuid,jsonb)','public.rpc_delete_claim_view(uuid,uuid)','public.rpc_refresh_claim_notifications(uuid)'] LOOP
  o:=to_regprocedure(s);IF o IS NULL THEN RAISE EXCEPTION 'F10 missing RPC %',s;END IF;
  IF NOT EXISTS(SELECT 1 FROM pg_proc WHERE oid=o AND prosecdef AND proconfig@>ARRAY['search_path=pg_catalog, public']::text[]) THEN RAISE EXCEPTION 'F10 unsafe RPC %',s;END IF;
  IF NOT has_function_privilege('authenticated',o,'EXECUTE') OR has_function_privilege('anon',o,'EXECUTE') OR has_function_privilege('service_role',o,'EXECUTE') OR pg_get_functiondef(o)~*'\mSQLERRM\M' THEN RAISE EXCEPTION 'F10 RPC ACL/error %',s;END IF;
 END LOOP;
 FOREACH s IN ARRAY ARRAY['private.f10_admin(uuid)','private.f10_business_year(uuid,timestamptz)','private.f10_next_claim_number(uuid,integer)','private.f10_seed_policies(uuid)','private.f10_policy(uuid,text,text)','private.f10_sla(public.service_claims,timestamptz)','private.f10_add_event(public.service_claims,text,text,jsonb,timestamptz)','private.f10_seed_automation_rules(uuid)','private.f10_materialize_claim_notifications(uuid,timestamptz)'] LOOP
  o:=to_regprocedure(s);IF o IS NULL OR has_function_privilege('authenticated',o,'EXECUTE') OR has_function_privilege('anon',o,'EXECUTE') OR has_function_privilege('service_role',o,'EXECUTE') THEN RAISE EXCEPTION 'F10 private ACL %',s;END IF;
 END LOOP;
 IF (SELECT count(*) FROM cron.job WHERE jobname LIKE 'rotero-f7-%')<>2 OR NOT EXISTS(SELECT 1 FROM cron.job WHERE jobname='rotero-f7-automation-hourly' AND schedule='0 * * * *') OR NOT EXISTS(SELECT 1 FROM cron.job WHERE jobname='rotero-f7-daily-digest' AND schedule='15 12 * * *') THEN RAISE EXCEPTION 'F10 changed F7 cron';END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.automation_rules'::regclass AND conname='automation_rules_claims_admin_only_check') THEN RAISE EXCEPTION 'F10 claims automation role guard missing';END IF;
 IF pg_get_functiondef('public.rpc_get_public_tracking(text)'::regprocedure)~*'(service_claim|claims)' OR pg_get_functiondef('public.rpc_get_driver_view(text)'::regprocedure)~*'(service_claim|claims)' THEN RAISE EXCEPTION 'F10 Tracking mutation/leak';END IF;
 IF (SELECT count(*) FROM pg_proc WHERE pronamespace='public'::regnamespace AND proname LIKE 'rpc_%claim%')<>30 THEN RAISE EXCEPTION 'F10 exact pg_proc surface collision/count';END IF;
END $contract$;

DO $fixtures$
DECLARE tenant uuid;other uuid;admin_id uuid:=gen_random_uuid();finance_id uuid:=gen_random_uuid();operator_id uuid:=gen_random_uuid();outsider uuid:=gen_random_uuid();customer uuid;provider uuid;other_customer uuid;operation_id uuid;incident_id uuid;customer_contact uuid;provider_contact uuid;
BEGIN
 INSERT INTO auth.users(instance_id,id,aud,role,email,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at) VALUES
 ('00000000-0000-0000-0000-000000000000',admin_id,'authenticated','authenticated','f10-admin@example.invalid',now(),'{}','{}',now(),now()),('00000000-0000-0000-0000-000000000000',finance_id,'authenticated','authenticated','f10-finance@example.invalid',now(),'{}','{}',now(),now()),('00000000-0000-0000-0000-000000000000',operator_id,'authenticated','authenticated','f10-operator@example.invalid',now(),'{}','{}',now(),now()),('00000000-0000-0000-0000-000000000000',outsider,'authenticated','authenticated','f10-outsider@example.invalid',now(),'{}','{}',now(),now());
 INSERT INTO public.tenants(name,slug) VALUES('F10 Tenant','f10-tenant'),('F10 Other','f10-other');SELECT id INTO tenant FROM public.tenants WHERE slug='f10-tenant';SELECT id INTO other FROM public.tenants WHERE slug='f10-other';
 INSERT INTO public.memberships(tenant_id,user_id,role) VALUES(tenant,admin_id,'admin'),(tenant,finance_id,'finance'),(tenant,operator_id,'operator');
 INSERT INTO public.customers(tenant_id,display_name) VALUES(tenant,'Cliente F10') RETURNING id INTO customer;INSERT INTO public.customers(tenant_id,display_name) VALUES(other,'Cliente ajeno F10') RETURNING id INTO other_customer;INSERT INTO public.logistics_providers(tenant_id,display_name) VALUES(tenant,'Proveedor F10') RETURNING id INTO provider;
 INSERT INTO public.operations(tenant_id,reference_code,status,execution_type,customer_id,provider_id,provider_name,pricing_currency,customer_price_amount,provider_cost_amount) VALUES(tenant,'OP-F10-001','planned','third_party',customer,provider,'Proveedor F10','MXN',1500,1000) RETURNING id INTO operation_id;
 INSERT INTO public.operation_incidents(tenant_id,operation_id,category,title,description,is_blocking,reported_by,reported_at) VALUES(tenant,operation_id,'delay','Demora F10','Evento operativo separado',true,admin_id,now()-interval '2 days') RETURNING id INTO incident_id;
 INSERT INTO public.business_contacts(tenant_id,customer_id,name,contact_role,created_by) VALUES(tenant,customer,'Cliente Contacto','commercial',admin_id) RETURNING id INTO customer_contact;INSERT INTO public.business_contacts(tenant_id,provider_id,name,contact_role,created_by) VALUES(tenant,provider,'Proveedor Contacto','operations',admin_id) RETURNING id INTO provider_contact;
 PERFORM set_config('f10.tenant',tenant::text,true);PERFORM set_config('f10.other',other::text,true);PERFORM set_config('f10.admin',admin_id::text,true);PERFORM set_config('f10.finance',finance_id::text,true);PERFORM set_config('f10.operator',operator_id::text,true);PERFORM set_config('f10.outsider',outsider::text,true);PERFORM set_config('f10.customer',customer::text,true);PERFORM set_config('f10.other_customer',other_customer::text,true);PERFORM set_config('f10.provider',provider::text,true);PERFORM set_config('f10.operation',operation_id::text,true);PERFORM set_config('f10.incident',incident_id::text,true);PERFORM set_config('f10.customer_contact',customer_contact::text,true);PERFORM set_config('f10.provider_contact',provider_contact::text,true);
END $fixtures$;

DO $admin$
DECLARE tenant uuid:=current_setting('f10.tenant')::uuid;operation_id uuid:=current_setting('f10.operation')::uuid;incident_id uuid:=current_setting('f10.incident')::uuid;claim1 uuid;claim2 uuid;action_id uuid;r jsonb;n1 text;n2 text;incident_status text;handoff jsonb;
BEGIN
 PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('f10.admin'),'role','authenticated')::text,true);
 IF (SELECT count(*) FROM public.claim_service_policies WHERE tenant_id=tenant)<>4 OR (SELECT count(*) FROM public.automation_rules WHERE tenant_id=tenant AND module='claims')<>4 THEN RAISE EXCEPTION 'F10 safe seed';END IF;
 r:=public.rpc_create_service_claim_from_incident(incident_id,'{"claim_type":"delay","priority":"critical"}');claim1:=(r->>'id')::uuid;n1:=r->>'claim_number';IF claim1 IS NULL OR n1!~'^CLM-[0-9]{4}-[0-9]{6}$' THEN RAISE EXCEPTION 'F10 incident claim %',r;END IF;
 SELECT status INTO incident_status FROM public.operation_incidents WHERE id=incident_id;IF incident_status<>'open' OR (SELECT source_incident_id FROM public.service_claims WHERE id=claim1)<>incident_id THEN RAISE EXCEPTION 'F10 incident mutated/not linked';END IF;
 r:=public.rpc_create_service_claim(tenant,jsonb_build_object('customer_id',current_setting('f10.customer'),'provider_id',current_setting('f10.provider'),'claim_type','service_quality','priority','high','subject','Atención deficiente','description','Expediente de servicio F10','reported_at',now()-interval '10 days'));claim2:=(r->>'id')::uuid;n2:=r->>'claim_number';IF claim2 IS NULL OR n1=n2 OR right(n2,6)::int<>right(n1,6)::int+1 THEN RAISE EXCEPTION 'F10 tenant sequence % %',n1,n2;END IF;
 IF public.rpc_create_service_claim(tenant,'{"claim_type":"other","subject":"Sin contexto","description":"No permitido"}')->>'error'<>'missing_context' OR public.rpc_create_service_claim(tenant,jsonb_build_object('customer_id',current_setting('f10.other_customer'),'claim_type','other','subject','Ajeno','description','Cruce tenant'))->>'error'<>'invalid_customer' THEN RAISE EXCEPTION 'F10 context/tenant gate';END IF;
 r:=public.rpc_get_service_claim(claim1);IF r#>>'{source_incident,title}'<>'Demora F10' OR r#>>'{operation,reference}'<>'OP-F10-001' OR r#>>'{operation,provider_cost}'<>'1000.00' THEN RAISE EXCEPTION 'F10 context 360 %',r;END IF;
 PERFORM public.rpc_log_claim_contact(claim1,'customer',current_setting('f10.customer_contact')::uuid,'email','Primera respuesta trazable',now());IF (SELECT first_responded_at IS NULL FROM public.service_claims WHERE id=claim1) THEN RAISE EXCEPTION 'F10 first response';END IF;
 IF public.rpc_log_claim_contact(claim1,'provider',current_setting('f10.customer_contact')::uuid,'phone','Contacto cruzado',now())->>'error'<>'invalid_contact' THEN RAISE EXCEPTION 'F10 contact ownership';END IF;
 PERFORM public.rpc_update_claim_classification(claim1,'provider','provider_execution','Clasificación operativa revisada');r:=public.rpc_upsert_claim_action(claim1,NULL,jsonb_build_object('title','Solicitar plan preventivo','due_at',now()-interval '1 day'));action_id:=(r->>'id')::uuid;IF action_id IS NULL THEN RAISE EXCEPTION 'F10 action';END IF;
 IF public.rpc_update_claim_action_status(action_id,'done',NULL)->>'error'<>'invalid_action_status' THEN RAISE EXCEPTION 'F10 action evidence required';END IF;PERFORM public.rpc_update_claim_action_status(action_id,'done','Plan recibido y validado');
 PERFORM public.rpc_upsert_claim_financial(claim1,NULL,'{"exposure_type":"customer_claim","amount":1200,"currency":"MXN","status":"estimated"}');PERFORM public.rpc_upsert_claim_financial(claim1,NULL,'{"exposure_type":"provider_recovery","amount":100,"currency":"USD","status":"estimated"}');r:=public.rpc_get_service_claim(claim1);IF jsonb_array_length(r->'exposure_by_currency')<>2 THEN RAISE EXCEPTION 'F10 no fake FX %',r->'exposure_by_currency';END IF;
 PERFORM public.rpc_record_claim_settlement(claim1,jsonb_build_object('amount',500,'currency','MXN','settlement_type','operational_agreement','date',current_date,'notes','Acuerdo sin efecto contable automático'));handoff:=public.rpc_get_claim_finance_handoff(claim1);IF (handoff->>'accounting_mutated')::boolean OR handoff->>'route' NOT LIKE '/finance%' THEN RAISE EXCEPTION 'F10 F4 handoff %',handoff;END IF;
 PERFORM public.rpc_transition_service_claim(claim1,'triage');PERFORM public.rpc_transition_service_claim(claim1,'investigating');IF public.rpc_transition_service_claim(claim1,'resolved',NULL)->>'error'<>'reason_required' THEN RAISE EXCEPTION 'F10 resolution evidence gate';END IF;PERFORM public.rpc_transition_service_claim(claim1,'resolved','Demora documentada y acciones concluidas');PERFORM public.rpc_transition_service_claim(claim1,'closed','Cierre confirmado');PERFORM public.rpc_reopen_service_claim(claim1,'Cliente aporta evidencia adicional');IF (SELECT status FROM public.service_claims WHERE id=claim1)<>'investigating' OR NOT EXISTS(SELECT 1 FROM public.service_claim_events WHERE claim_id=claim1 AND event_type='reopened' AND metadata?'prior_resolution') THEN RAISE EXCEPTION 'F10 reopen history';END IF;
 IF jsonb_array_length(public.rpc_list_service_claims(tenant,'{"priority":"critical"}'))<>1 OR jsonb_array_length(public.rpc_search_claims(tenant,'OP-F10',10))=0 OR jsonb_array_length(public.rpc_list_partner_claims('customer',current_setting('f10.customer')::uuid,50))<>2 OR jsonb_array_length(public.rpc_export_claims(tenant,'{}'))<>2 THEN RAISE EXCEPTION 'F10 list/search/partner/export';END IF;
 r:=public.rpc_save_claim_view(tenant,NULL,'{"name":"Críticas","filters":{"priority":"critical"},"sort":{},"is_default":true}');IF r->>'id' IS NULL OR jsonb_array_length(public.rpc_list_claim_saved_views(tenant))<>1 THEN RAISE EXCEPTION 'F10 saved views';END IF;
 IF public.rpc_get_claim_reporting(tenant,now()-interval '30 days',now()+interval '1 day')->'provider_recurrence' IS NULL OR public.rpc_get_claims_dashboard(tenant,now()-interval '30 days',now()+interval '1 day')->'exposure_by_currency' IS NULL THEN RAISE EXCEPTION 'F10 reporting/dashboard';END IF;
 PERFORM set_config('f10.claim1',claim1::text,true);PERFORM set_config('f10.claim2',claim2::text,true);
END $admin$;

DO $denials$
DECLARE tenant uuid:=current_setting('f10.tenant')::uuid;claim1 uuid:=current_setting('f10.claim1')::uuid;
BEGIN
 PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('f10.finance'),'role','authenticated')::text,true);IF public.rpc_list_service_claims(tenant,'{}')->>'error'<>'unauthorized' OR public.rpc_get_service_claim(claim1)->>'error'<>'unauthorized' OR public.rpc_search_claims(tenant,'F10',10)->>'error'<>'unauthorized' OR public.rpc_get_claims_dashboard(tenant,NULL,NULL)->>'error'<>'unauthorized' THEN RAISE EXCEPTION 'F10 Finance leak';END IF;
 PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('f10.operator'),'role','authenticated')::text,true);IF public.rpc_create_service_claim(tenant,'{}')->>'error'<>'unauthorized' THEN RAISE EXCEPTION 'F10 operator write';END IF;
 PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('f10.outsider'),'role','authenticated')::text,true);IF public.rpc_export_claims(tenant,'{}')->>'error'<>'unauthorized' THEN RAISE EXCEPTION 'F10 outsider leak';END IF;
END $denials$;

DO $automation$
DECLARE tenant uuid:=current_setting('f10.tenant')::uuid;admin_id uuid:=current_setting('f10.admin')::uuid;finance_id uuid:=current_setting('f10.finance')::uuid;claim1 uuid:=current_setting('f10.claim1')::uuid;count1 integer;
BEGIN
 UPDATE public.service_claims SET first_responded_at=NULL,response_due_at=now()-interval '2 hours',resolution_due_at=now()-interval '1 hour',priority='critical',status='investigating' WHERE id=claim1;
 PERFORM private.f10_materialize_claim_notifications(tenant,now());PERFORM private.f10_materialize_claim_notifications(tenant,now());SELECT count(*) INTO count1 FROM public.internal_notifications WHERE tenant_id=tenant AND user_id=admin_id AND area='claims' AND resolved_at IS NULL;IF count1<>5 OR EXISTS(SELECT 1 FROM public.internal_notifications WHERE tenant_id=tenant AND user_id=finance_id AND area='claims') OR EXISTS(SELECT 1 FROM public.internal_notifications GROUP BY tenant_id,user_id,fingerprint HAVING count(*)>1) THEN RAISE EXCEPTION 'F10 notifications idempotency/isolation %',count1;END IF;
 UPDATE public.service_claims SET first_responded_at=now(),status='resolved',resolved_at=now(),resolution_summary='Resuelto para materialización' WHERE id=claim1;PERFORM private.f10_materialize_claim_notifications(tenant,now());IF EXISTS(SELECT 1 FROM public.internal_notifications WHERE tenant_id=tenant AND area='claims' AND related_entity_id=claim1::text AND resolved_at IS NULL) THEN RAISE EXCEPTION 'F10 notification auto resolution';END IF;
END $automation$;

ROLLBACK;
