import { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { listPartnerHistoryPage } from '@/services/rates.service';
import type { ClaimListItem } from '@/types/claims';
import { CLAIM_PRIORITY_LABELS, CLAIM_STATUS_LABELS, CLAIM_TYPE_LABELS } from '@/utils/presentationLabels';

const RESPONSIBILITY_LABELS:Record<string,string>={undetermined:'Por determinar',internal:'Interna',provider:'Proveedor',customer:'Cliente',shared:'Compartida',external_other:'Externa',no_fault:'Sin atribución'};
import type { PartnerHistoryCursor } from '@/types/rates';

export function PartnerClaimsPanel({tenantId,entityType,entityId}:{tenantId:string;entityType:'customer'|'provider';entityId:string}){const[items,setItems]=useState<ClaimListItem[]>([]),[cursor,setCursor]=useState<PartnerHistoryCursor|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');const requestId=useRef(0);const load=async(more=false)=>{const current=++requestId.current;setLoading(true);try{const page=await listPartnerHistoryPage(tenantId,entityType,entityId,'claims',more?cursor:null);if(current!==requestId.current)return;setItems(value=>more?[...value,...page.items as unknown as ClaimListItem[]]:page.items as unknown as ClaimListItem[]);setCursor(page.next_cursor);setError('')}catch(e){if(current===requestId.current)setError(e instanceof Error?e.message:'No fue posible cargar reclamaciones.')}finally{if(current===requestId.current)setLoading(false)}};useEffect(()=>{setItems([]);setCursor(null);void load(false)},[entityId,entityType,tenantId]);if(error)return <p className="rounded-lg bg-red-50 p-3 text-xs text-red-700">{error}</p>;return <div className="space-y-2">{!loading&&items.length===0?<p className="rounded-xl border border-dashed p-5 text-center text-xs text-slate-400">Sin reclamaciones relacionadas.</p>:items.map(item=><Link key={item.id} to={`/claims?claimId=${item.id}`} className="flex min-w-0 items-center justify-between gap-3 rounded-xl border p-3 hover:border-primary"><span className="min-w-0"><b className="block break-words text-xs">{item.claim_number} · {item.subject}</b><small className="break-words text-slate-400">{CLAIM_TYPE_LABELS[item.claim_type]} · {CLAIM_STATUS_LABELS[item.status]} · responsabilidad {RESPONSIBILITY_LABELS[item.responsibility??'undetermined']??'Por determinar'}</small><small className="block break-words text-slate-400">{item.exposure_by_currency?.map(value=>`${value.currency} ${Number(value.amount).toLocaleString()}`).join(' · ')||'Sin exposición estimada'}</small></span><span className={`shrink-0 rounded-full px-2 py-1 text-[9px] font-black uppercase ${item.priority==='critical'?'bg-red-100 text-red-700':'bg-slate-100 text-slate-600'}`}>{CLAIM_PRIORITY_LABELS[item.priority]}</span></Link>)}{cursor&&<button type="button" disabled={loading} onClick={()=>void load(true)} className="w-full rounded-lg border p-2 text-xs font-bold">{loading?'Cargando…':'Cargar reclamaciones anteriores'}</button>}</div>}
