import { AlertTriangle, Clock3 } from 'lucide-react';
import type { FinanceDueAlert } from '@/types/finance';
import { money, shortDate } from './financeUi';

export function DueAlertsPanel({ items, daysAhead, onDaysAhead, onOpen }: { items: FinanceDueAlert[]; daysAhead: number; onDaysAhead: (days: number) => void; onOpen: (id: string) => void }) {
    return <section className="rounded-2xl border bg-white"><header className="flex flex-wrap items-center justify-between gap-3 border-b p-5"><div><h2 className="font-black text-slate-800">Vencimientos AR y AP</h2><p className="text-xs text-slate-400">Cobranza y obligaciones en la misma agenda, sin mezclar direcciones.</p></div><select value={daysAhead} onChange={(e) => onDaysAhead(Number(e.target.value))} className="rounded-xl border px-3 py-2 text-xs"><option value={7}>7 días</option><option value={14}>14 días</option><option value={30}>30 días</option><option value={60}>60 días</option></select></header>
        <div className="grid gap-3 p-5 md:grid-cols-2">{items.length === 0 ? <p className="col-span-full py-12 text-center text-sm text-slate-400">Sin vencimientos en esta ventana.</p> : items.map((item) => <button key={item.id} onClick={() => onOpen(item.id)} className={`rounded-xl border p-4 text-left ${item.alert_type === 'overdue' ? 'border-red-200 bg-red-50/50' : 'border-amber-200 bg-amber-50/50'}`}><div className="flex items-start justify-between"><span className={`inline-flex items-center gap-1 text-[10px] font-bold uppercase ${item.alert_type === 'overdue' ? 'text-red-700' : 'text-amber-700'}`}>{item.alert_type === 'overdue' ? <AlertTriangle size={13} /> : <Clock3 size={13} />}{item.alert_type === 'overdue' ? `${Math.abs(item.days_to_due)} días vencida` : `vence en ${item.days_to_due} días`}</span><span className="rounded-full bg-white px-2 py-1 text-[10px] font-bold text-slate-500">{item.direction === 'ar' ? 'Por cobrar' : 'Por pagar'}</span></div><p className="mt-3 font-bold text-slate-700">{item.counterparty_name}</p><p className="mt-1 text-xs text-slate-400">{item.operation_reference ?? item.reference ?? 'Sin referencia'} · {shortDate(item.due_date)}</p><p className="mt-3 text-lg font-black text-slate-800">{money(item.balance_amount,item.currency)}</p></button>)}</div>
    </section>;
}
