import { useEffect, useState } from 'react';
import { AnimatePresence, motion } from 'motion/react';
import { AlertCircle, Banknote, ExternalLink, Loader2, X } from 'lucide-react';
import { Link } from 'react-router-dom';
import { EntityDocumentsPanel } from '@/components/documents/EntityDocumentsPanel';
import { getFinanceInvoiceDetail, voidFinanceInvoice } from '@/services/finance.service';
import type { FinanceInvoice, FinanceInvoiceDetail } from '@/types/finance';
import { money, shortDate, STATUS_LABEL, STATUS_STYLE } from './financeUi';

export function FinanceInvoiceDrawer({ tenantId, invoice, onClose, onPay, onChanged }: { tenantId: string; invoice: FinanceInvoice | null; onClose: () => void; onPay: (invoice: FinanceInvoice) => void; onChanged: () => void }) {
    const [detail, setDetail] = useState<FinanceInvoiceDetail | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
    const [voiding, setVoiding] = useState(false); const [reason, setReason] = useState(''); const [saving, setSaving] = useState(false);
    useEffect(() => { if (!invoice) return; setLoading(true); setError(null); setDetail(null); setVoiding(false); getFinanceInvoiceDetail(tenantId, invoice.id).then(setDetail).catch((cause) => setError(cause instanceof Error ? cause.message : 'No fue posible abrir la cuenta.')).finally(() => setLoading(false)); }, [invoice, tenantId]);
    const voidInvoice = async () => { if (!detail || reason.trim().length < 5) return; setSaving(true); setError(null); try { await voidFinanceInvoice(tenantId, detail.invoice.id, reason); setVoiding(false); onChanged(); onClose(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No fue posible anular la cuenta.'); } finally { setSaving(false); } };
    const current = detail?.invoice.effective_status ?? detail?.invoice.status;
    return <AnimatePresence>{invoice && <div className="fixed inset-0 z-40 bg-slate-950/40 backdrop-blur-sm"><motion.button aria-label="Cerrar expediente" className="absolute inset-0" onClick={onClose} /><motion.aside initial={{ x: 720 }} animate={{ x: 0 }} exit={{ x: 720 }} className="absolute inset-y-0 right-0 flex w-full max-w-2xl flex-col bg-slate-50 shadow-2xl">
        <header className="flex items-center justify-between border-b bg-white px-6 py-4"><div><h2 className="font-black text-slate-800">Expediente financiero</h2><p className="text-xs text-slate-400">{invoice.reference ?? invoice.id}</p></div><button onClick={onClose} className="rounded-lg bg-slate-100 p-2"><X size={17} /></button></header>
        <div className="flex-1 space-y-4 overflow-y-auto p-5">{loading ? <div className="flex justify-center p-16"><Loader2 className="animate-spin text-primary" /></div> : error && !detail ? <div className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</div> : detail && current ? <>
            {error && <div className="flex gap-2 rounded-xl bg-red-50 p-3 text-xs text-red-700"><AlertCircle size={15} />{error}</div>}
            <section className="rounded-2xl border bg-white p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{detail.invoice.direction === 'ar' ? 'Cliente · por cobrar' : 'Proveedor · por pagar'}</p><h3 className="mt-1 text-xl font-black text-slate-800">{detail.invoice.counterparty_name}</h3><p className="mt-1 text-xs text-slate-400">Vence {shortDate(detail.invoice.due_date)}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${STATUS_STYLE[current]}`}>{STATUS_LABEL[current]}</span></div>
                <div className="mt-5 grid grid-cols-3 gap-3"><Metric label="Importe" value={money(detail.invoice.amount, detail.invoice.currency)} /><Metric label="Aplicado" value={money((detail.invoice.paid_amount ?? 0)+(detail.invoice.credit_amount ?? 0), detail.invoice.currency)} /><Metric label="Saldo" value={money(detail.invoice.balance_amount, detail.invoice.currency)} /></div>
                {detail.invoice.currency === 'USD' && <p className="mt-3 rounded-lg bg-amber-50 p-2 text-xs text-amber-800">TC {detail.invoice.exchange_rate} · {shortDate(detail.invoice.exchange_rate_date)} · histórico inmutable</p>}
                <div className="mt-4 flex flex-wrap gap-2">{detail.invoice.operation_id && <Link to={`/operations?operationId=${detail.invoice.operation_id}`} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs font-bold text-slate-600">Operación {detail.invoice.operation_reference}<ExternalLink size={12} /></Link>}{detail.invoice.linked_cfdi_id && <Link to={`/billing?cfdiId=${detail.invoice.linked_cfdi_id}`} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs font-bold text-indigo-600">Abrir en Billing<ExternalLink size={12} /></Link>}{['open','overdue'].includes(current) && <button onClick={() => onPay(detail.invoice)} className="inline-flex items-center gap-1 rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white"><Banknote size={13} />Registrar pago</button>}</div>
            </section>
            <section className="rounded-2xl border bg-white p-5"><h3 className="text-sm font-black text-slate-800">Pagos y créditos</h3><div className="mt-3 divide-y rounded-xl border">{detail.payments.length === 0 && detail.credit_notes.length === 0 ? <p className="p-4 text-center text-xs text-slate-400">Sin aplicaciones.</p> : <>{detail.payments.map((payment) => <div key={payment.id} className="flex items-center justify-between p-3 text-xs"><div><strong className="text-slate-700">{payment.method}</strong><p className="text-[10px] text-slate-400">{shortDate(payment.paid_at)} · {payment.bank_reference ?? 'Sin referencia bancaria'}</p></div><strong className="text-emerald-700">{money(payment.amount,payment.currency)}</strong></div>)}{detail.credit_notes.map((credit) => <div key={credit.id} className="flex items-center justify-between p-3 text-xs"><div><strong className="text-slate-700">Nota de crédito · {credit.status}</strong><p className="text-[10px] text-slate-400">{credit.folio ?? credit.id}</p></div><strong className="text-indigo-700">-{money(credit.total,credit.currency)}</strong></div>)}</>}</div></section>
            <section className="rounded-2xl border bg-white p-5"><h3 className="text-sm font-black text-slate-800">Handoff de complementos</h3><p className="mt-1 text-xs text-slate-400">Preparación en Finance; ejecución fiscal en Billing.</p><div className="mt-3 space-y-2">{detail.payment_complements.length === 0 ? <p className="rounded-xl border border-dashed p-4 text-center text-xs text-slate-400">Sin complemento preparado.</p> : detail.payment_complements.map((item) => <div key={item.id} className="flex items-center justify-between rounded-xl border p-3 text-xs"><span>{shortDate(item.payment_date)} · {item.method}</span><span className="rounded-full bg-indigo-50 px-2 py-1 font-bold text-indigo-700">{item.status}</span></div>)}</div></section>
            <EntityDocumentsPanel tenantId={tenantId} sourceModule="finance" entityType="finance_invoice" entityId={detail.invoice.id} title="Documentos de la cuenta" />
            <section className="rounded-2xl border bg-white p-5"><h3 className="text-sm font-black text-slate-800">Línea de tiempo derivada</h3><div className="mt-3 space-y-3">{detail.timeline.map((item, index) => <div key={`${item.event_type}-${index}`} className="flex gap-3 text-xs"><span className="mt-1 h-2 w-2 rounded-full bg-primary" /><div><strong className="text-slate-700">{item.event_type.replaceAll('_',' ')}</strong><p className="text-[10px] text-slate-400">{shortDate(item.occurred_at)}</p></div></div>)}</div></section>
            {!['paid','void'].includes(current) && <section className="rounded-2xl border border-red-100 bg-white p-5">{voiding ? <div className="space-y-3"><label className="block text-xs font-bold text-red-700">Motivo auditado<textarea value={reason} onChange={(e) => setReason(e.target.value)} className="mt-1 min-h-20 w-full rounded-xl border border-red-200 p-3 font-normal text-slate-700" /></label><div className="flex gap-2"><button onClick={() => setVoiding(false)} className="rounded-lg bg-slate-100 px-3 py-2 text-xs font-bold">Volver</button><button disabled={saving || reason.trim().length<5} onClick={() => void voidInvoice()} className="rounded-lg bg-red-600 px-3 py-2 text-xs font-bold text-white disabled:opacity-50">Confirmar anulación</button></div></div> : <button onClick={() => setVoiding(true)} className="text-xs font-bold text-red-600">Anular cuenta con motivo</button>}</section>}
        </> : null}</div>
    </motion.aside></div>}</AnimatePresence>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] uppercase text-slate-400">{label}</p><p className="mt-1 text-sm font-black text-slate-700">{value}</p></div>; }
