import { useEffect, useMemo, useState, type FormEvent, type InputHTMLAttributes } from 'react';
import { AlertCircle, Loader2, X } from 'lucide-react';
import { createFinanceInvoice, getOperationFinanceSummary } from '@/services/finance.service';
import type { FinanceCurrency, InvoiceDirection, OperationFinanceSummary } from '@/types/finance';
import type { Operation } from '@/types/operations';
import { money } from './financeUi';

export function InvoiceCreateModal({ tenantId, direction, operations, partnerId, partnerName='', suggestedTerms=0, onClose, onSaved }: { tenantId: string; direction: InvoiceDirection; operations: Operation[]; partnerId?:string|null; partnerName?:string; suggestedTerms?:number; onClose: () => void; onSaved: () => void }) {
    const suggestedDueDate=()=>{if(!suggestedTerms)return '';const value=new Date();value.setHours(12,0,0,0);value.setDate(value.getDate()+suggestedTerms);return value.toISOString().slice(0,10);};
    const [operationId,setOperationId]=useState(''); const [counterparty,setCounterparty]=useState(partnerName); const [reference,setReference]=useState(''); const [amount,setAmount]=useState('');
    const [currency,setCurrency]=useState<FinanceCurrency>('MXN'); const [status,setStatus]=useState<'draft'|'open'>('open'); const [dueDate,setDueDate]=useState(suggestedDueDate);
    const [rate,setRate]=useState(''); const [rateDate,setRateDate]=useState(''); const [notes,setNotes]=useState(''); const [override,setOverride]=useState(false); const [overrideReason,setOverrideReason]=useState('');
    const [summary,setSummary]=useState<OperationFinanceSummary|null>(null);
    const [saving,setSaving]=useState(false); const [error,setError]=useState<string|null>(null);
    const operation=useMemo(()=>operations.find((item)=>(item.db_id??item.id)===operationId),[operationId,operations]);
    const expected=direction==='ar'?operation?.customer_price_amount:operation?.provider_cost_amount;
    useEffect(()=>{if(!operationId){setSummary(null);return;}getOperationFinanceSummary(tenantId,operationId).then((value)=>{setSummary(value);setAmount(String(direction==='ar'?value.remaining_ar_to_register:value.remaining_ap_to_register));}).catch(()=>setSummary(null));},[direction,operationId,tenantId]);
    const selectOperation=(id:string)=>{setOperationId(id);const selected=operations.find((item)=>(item.db_id??item.id)===id);if(selected){setCurrency((selected.pricing_currency==='USD'?'USD':'MXN'));const value=direction==='ar'?selected.customer_price_amount:selected.provider_cost_amount;if(value!=null)setAmount(String(value));setCounterparty('');}};
    const submit=async(event:FormEvent)=>{event.preventDefault();setSaving(true);setError(null);try{await createFinanceInvoice(tenantId,{direction,operation_id:operationId||undefined,counterparty_name:counterparty||undefined,...(partnerId?direction==='ar'?{customer_id:partnerId}:{provider_id:partnerId}:{}),reference:reference||undefined,amount:Number(amount),currency,status,due_date:dueDate||undefined,exchange_rate:rate?Number(rate):undefined,exchange_rate_date:rateDate||undefined,notes:notes||undefined,over_registration_override:override,over_registration_reason:overrideReason||undefined});onSaved();}catch(cause){setError(cause instanceof Error?cause.message:'No fue posible crear la cuenta.');}finally{setSaving(false);}};
    return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4 backdrop-blur-sm"><form onSubmit={submit} className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><header className="mb-5 flex items-center justify-between"><div><h2 className="text-lg font-black text-slate-800">Nueva cuenta {direction==='ar'?'por cobrar':'por pagar'}</h2><p className="text-xs text-slate-400">Registro explícito; nunca se genera al cerrar una operación.</p></div><button type="button" onClick={onClose}><X size={18}/></button></header>
        {error&&<div className="mb-4 flex gap-2 rounded-xl bg-red-50 p-3 text-xs font-semibold text-red-700"><AlertCircle size={15}/>{error}</div>}
        <div className="space-y-4"><label className="block text-xs font-bold text-slate-500">Operación opcional<select value={operationId} onChange={(e)=>selectOperation(e.target.value)} className="mt-1 w-full rounded-xl border bg-slate-50 px-3 py-2.5 text-sm font-normal"><option value="">Cuenta sin operación</option>{operations.map((item)=><option key={item.db_id??item.id} value={item.db_id??item.id}>{item.reference_code??item.id} · {item.client}</option>)}</select></label>
        {operation?<div className="grid grid-cols-2 gap-3 rounded-xl border border-indigo-100 bg-indigo-50 p-3 text-xs sm:grid-cols-4"><Metric label="Esperado" value={money(expected,operation.pricing_currency)}/><Metric label="Registrado" value={money(direction==='ar'?summary?.registered_ar:summary?.registered_ap,operation.pricing_currency)}/><Metric label="Por registrar" value={money(direction==='ar'?summary?.remaining_ar_to_register:summary?.remaining_ap_to_register,operation.pricing_currency)}/><Metric label="Moneda" value={String(operation.pricing_currency??'MXN')}/></div>:<Field label="Contraparte *" value={counterparty} onChange={setCounterparty} required/>}
        <div className="grid gap-4 sm:grid-cols-2"><Field label="Referencia" value={reference} onChange={setReference}/><Field label="Vencimiento" type="date" value={dueDate} onChange={setDueDate}/><Field label="Importe *" type="number" min="0.01" step="0.01" value={amount} onChange={setAmount} required/><label className="text-xs font-bold text-slate-500">Moneda<select disabled={Boolean(operation)} value={currency} onChange={(e)=>setCurrency(e.target.value as FinanceCurrency)} className="mt-1 w-full rounded-xl border bg-slate-50 px-3 py-2.5 text-sm font-normal"><option>MXN</option><option>USD</option></select></label><label className="text-xs font-bold text-slate-500">Estado inicial<select value={status} onChange={(e)=>setStatus(e.target.value as 'draft'|'open')} className="mt-1 w-full rounded-xl border bg-slate-50 px-3 py-2.5 text-sm font-normal"><option value="open">Abierta</option><option value="draft">Borrador</option></select></label></div>
        {currency==='USD'&&status==='open'&&<div className="grid gap-4 sm:grid-cols-2"><Field label="Tipo de cambio *" type="number" min="0.000001" step="0.000001" value={rate} onChange={setRate} required/><Field label="Fecha TC *" type="date" value={rateDate} onChange={setRateDate} required/></div>}
        {operation&&<label className="flex items-start gap-3 rounded-xl border p-3 text-xs text-slate-600"><input type="checkbox" checked={override} onChange={(e)=>setOverride(e.target.checked)}/><span><strong>Autorizar excedente auditado</strong><br/>Sólo si el registro supera el importe esperado vigente de la operación.</span></label>}{override&&<Field label="Razón del excedente *" value={overrideReason} onChange={setOverrideReason} minLength={5} required/>}
        <label className="block text-xs font-bold text-slate-500">Notas<textarea value={notes} onChange={(e)=>setNotes(e.target.value)} className="mt-1 min-h-20 w-full rounded-xl border bg-slate-50 p-3 text-sm font-normal"/></label></div>
        <div className="mt-6 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-xl px-4 py-2.5 text-sm font-bold text-slate-500">Cancelar</button><button disabled={saving||Number(amount)<=0||(!operation&&!counterparty.trim())} className="rounded-xl bg-primary px-5 py-2.5 text-sm font-bold text-white disabled:opacity-50">{saving?<Loader2 size={16} className="animate-spin"/>:'Crear cuenta'}</button></div>
    </form></div>;
}
function Field({label,value,onChange,type='text',...props}:{label:string;value:string;onChange:(value:string)=>void;type?:string}&Omit<InputHTMLAttributes<HTMLInputElement>,'value'|'onChange'>){return <label className="block text-xs font-bold text-slate-500">{label}<input {...props} type={type} value={value} onChange={(e)=>onChange(e.target.value)} className="mt-1 w-full rounded-xl border bg-slate-50 px-3 py-2.5 text-sm font-normal"/></label>}
function Metric({label,value}:{label:string;value:string}){return <div><p className="text-[10px] text-indigo-500">{label}</p><strong className="text-indigo-900">{value}</strong></div>}
