import { useEffect, useState, type FormEvent, type InputHTMLAttributes } from 'react';
import { AnimatePresence, motion } from 'motion/react';
import { AlertCircle, Loader2, X } from 'lucide-react';
import { SemanticPanel } from '@/components/SemanticPanel';
import { recordPayment } from '@/services/finance.service';
import type { FinanceInvoice, PaymentMethod } from '@/types/finance';
import { money } from './financeUi';

export function PaymentDrawer({ tenantId, invoice, onClose, onSaved }: { tenantId: string; invoice: FinanceInvoice | null; onClose: () => void; onSaved: () => void }) {
    const [amount, setAmount] = useState(''); const [paidAt, setPaidAt] = useState(''); const [method, setMethod] = useState<PaymentMethod>('transfer');
    const [bankReference, setBankReference] = useState(''); const [note, setNote] = useState(''); const [prepare, setPrepare] = useState(true);
    const [rate, setRate] = useState(''); const [rateDate, setRateDate] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
    useEffect(() => { if (!invoice) return; setAmount(String(invoice.balance_amount ?? invoice.amount)); setPaidAt(new Date().toISOString().slice(0,16)); setMethod('transfer'); setBankReference(''); setNote(''); setPrepare(invoice.direction === 'ar'); setRate(invoice.exchange_rate ? String(invoice.exchange_rate) : ''); setRateDate(invoice.exchange_rate_date ?? ''); setError(null); }, [invoice]);
    const submit = async (event: FormEvent) => { event.preventDefault(); if (!invoice) return; setSaving(true); setError(null); try { await recordPayment(tenantId, { invoice_id: invoice.id, amount: Number(amount), paid_at: new Date(paidAt).toISOString(), method, bank_reference: bankReference || undefined, note: note || undefined, currency: invoice.currency, exchange_rate: rate ? Number(rate) : undefined, exchange_rate_date: rateDate || undefined, prepare_complement: prepare }); onSaved(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No fue posible registrar el pago.'); } finally { setSaving(false); } };
    return <AnimatePresence>{invoice && <div className="fixed inset-0 z-50 bg-slate-950/40 backdrop-blur-sm"><motion.button aria-label="Cerrar pago" className="absolute inset-0" onClick={onClose} /><motion.aside role="dialog" aria-modal="true" aria-labelledby="payment-drawer-title" initial={{ x: 520 }} animate={{ x: 0 }} exit={{ x: 520 }} className="absolute inset-y-0 right-0 flex h-dvh w-full min-w-0 max-w-full flex-col bg-surface-card shadow-2xl sm:max-w-lg">
        <header className="flex min-w-0 shrink-0 items-center justify-between gap-3 border-b p-4 pt-[max(0.75rem,env(safe-area-inset-top))] sm:p-5"><div className="min-w-0"><h2 id="payment-drawer-title" className="break-words font-black text-slate-800">Registrar {invoice.direction === 'ar' ? 'cobro' : 'pago a proveedor'}</h2><p className="break-words text-xs leading-relaxed text-slate-400">Saldo protegido durante el registro · {money(invoice.balance_amount ?? invoice.amount, invoice.currency)}</p></div><button onClick={onClose} aria-label="Cerrar registro de pago" className="flex h-11 w-11 shrink-0 items-center justify-center rounded-lg bg-slate-100"><X size={17} /></button></header>
        <form onSubmit={submit} className="min-w-0 max-w-full flex-1 space-y-4 overflow-y-auto overscroll-contain p-4 pb-[max(1rem,env(safe-area-inset-bottom))] sm:p-6">{error && <div className="flex min-w-0 gap-2 rounded-xl bg-red-50 p-3 text-xs font-semibold text-red-700"><AlertCircle size={15} className="shrink-0" /><span className="min-w-0 break-words">{error}</span></div>}
            <SemanticPanel tone="success" className="p-3 text-xs leading-relaxed text-slate-600">No se permiten sobrepagos: si otro pago liquida la cuenta primero, el saldo se actualiza y este intento se rechaza.</SemanticPanel>
            <div className="grid gap-4 sm:grid-cols-2"><Field label={`Importe · ${invoice.currency}`} type="number" step="0.01" min="0.01" max={String(invoice.balance_amount ?? invoice.amount)} value={amount} onChange={setAmount} required /><Field label="Fecha del pago" type="datetime-local" value={paidAt} onChange={setPaidAt} required /></div>
            <label className="block text-xs font-bold text-slate-500">Método<select value={method} onChange={(e) => setMethod(e.target.value as PaymentMethod)} className="mt-1 w-full rounded-xl border bg-slate-50 px-3 py-2.5 text-sm font-normal"><option value="transfer">Transferencia</option><option value="cash">Efectivo</option><option value="card">Tarjeta</option><option value="other">Otro</option></select></label>
            <Field label="Referencia bancaria" value={bankReference} onChange={setBankReference} />
            {invoice.currency === 'USD' && <div className="grid gap-4 sm:grid-cols-2"><Field label="Tipo de cambio" type="number" step="0.000001" min="0.000001" value={rate} onChange={setRate} required /><Field label="Fecha del tipo de cambio" type="date" value={rateDate} onChange={setRateDate} required /></div>}
            <label className="block text-xs font-bold text-slate-500">Nota<textarea value={note} onChange={(e) => setNote(e.target.value)} className="mt-1 min-h-20 w-full rounded-xl border bg-slate-50 px-3 py-2.5 text-sm font-normal" /></label>
            {invoice.direction === 'ar' && <SemanticPanel tone="info" className="p-3"><label className="flex min-w-0 items-start gap-3 text-xs text-slate-600"><input type="checkbox" checked={prepare} onChange={(e) => setPrepare(e.target.checked)} className="mt-0.5 shrink-0" /><span className="min-w-0 break-words"><strong>Preparar complemento de pago.</strong><br />Finanzas crea el registro; la ejecución fiscal continúa exclusivamente en Facturación.</span></label></SemanticPanel>}
            <div className="grid min-w-0 grid-cols-1 gap-3 border-t pt-4 min-[360px]:grid-cols-3"><button type="button" onClick={onClose} className="min-w-0 rounded-xl bg-slate-100 px-3 py-2.5 text-sm font-bold text-slate-600">Cancelar</button><button disabled={saving || Number(amount) <= 0} className="min-w-0 rounded-xl bg-primary px-3 py-2.5 text-sm font-bold text-white disabled:opacity-50 min-[360px]:col-span-2">{saving ? <Loader2 className="mx-auto animate-spin" size={17} /> : 'Registrar de forma segura'}</button></div>
        </form>
    </motion.aside></div>}</AnimatePresence>;
}

function Field({ label, value, onChange, type='text', ...props }: { label: string; value: string; onChange: (value: string) => void; type?: string } & Omit<InputHTMLAttributes<HTMLInputElement>, 'value' | 'onChange'>) {
    return <label className="block min-w-0 text-xs font-bold text-slate-500">{label}<input {...props} type={type} value={value} onChange={(e) => onChange(e.target.value)} className="mt-1 w-full min-w-0 max-w-full rounded-xl border bg-slate-50 px-3 py-2.5 text-sm font-normal" /></label>;
}
