import { supabase } from '@/lib/supabase';
import type { Claim360, ClaimListItem, ClaimReferenceData, ClaimReporting, ClaimsDashboard } from '@/types/claims';
import type { DocumentFile } from '@/types/documents';
import type { AttentionItem } from '@/types/executive';

function result<T>(data:unknown,error:{message?:string}|null):T{if(error)throw new Error(error.message||'No fue posible comunicarse con Claims 360.');if(data&&typeof data==='object'&&'error'in data)throw new Error(String((data as {error:unknown}).error));return data as T;}
export async function listClaims(tenantId:string,filters:Record<string,unknown>={}){const{data,error}=await supabase.rpc('rpc_list_service_claims',{p_tenant_id:tenantId,p_filters:filters});return result<ClaimListItem[]>(data,error);}
export async function getClaim(id:string){const{data,error}=await supabase.rpc('rpc_get_service_claim',{p_claim_id:id});return result<Claim360>(data,error);}
export async function getClaimReferenceData(tenantId:string){const{data,error}=await supabase.rpc('rpc_get_claim_reference_data',{p_tenant_id:tenantId});return result<ClaimReferenceData>(data,error);}
export async function createClaim(tenantId:string,payload:Record<string,unknown>){const{data,error}=await supabase.rpc('rpc_create_service_claim',{p_tenant_id:tenantId,p_payload:payload});return result<{id:string;claim_number:string}>(data,error);}
export async function createClaimFromIncident(incidentId:string,payload:Record<string,unknown>){const{data,error}=await supabase.rpc('rpc_create_service_claim_from_incident',{p_incident_id:incidentId,p_payload:payload});return result<{id:string;claim_number:string}>(data,error);}
export async function transitionClaim(id:string,status:string,note?:string){const{data,error}=await supabase.rpc('rpc_transition_service_claim',{p_claim_id:id,p_to_status:status,p_note:note??null});return result(data,error);}
export async function reopenClaim(id:string,reason:string){const{data,error}=await supabase.rpc('rpc_reopen_service_claim',{p_claim_id:id,p_reason:reason});return result(data,error);}
export async function assignClaim(id:string,userId:string|null){const{data,error}=await supabase.rpc('rpc_assign_service_claim',{p_claim_id:id,p_user_id:userId});return result(data,error);}
export async function classifyClaim(id:string,responsibility:string,rootCause:string,note?:string){const{data,error}=await supabase.rpc('rpc_update_claim_classification',{p_claim_id:id,p_responsibility:responsibility,p_root_cause:rootCause,p_note:note??null});return result(data,error);}
export async function addClaimNote(id:string,note:string){const{data,error}=await supabase.rpc('rpc_add_claim_note',{p_claim_id:id,p_note:note});return result(data,error);}
export async function logClaimContact(id:string,payload:{party:string;contact_id:string;channel:string;summary:string;occurred_at?:string}){const{data,error}=await supabase.rpc('rpc_log_claim_contact',{p_claim_id:id,p_party:payload.party,p_contact_id:payload.contact_id,p_channel:payload.channel,p_summary:payload.summary,p_occurred_at:payload.occurred_at??new Date().toISOString()});return result(data,error);}
export async function upsertClaimAction(id:string,actionId:string|null,payload:Record<string,unknown>){const{data,error}=await supabase.rpc('rpc_upsert_claim_action',{p_claim_id:id,p_action_id:actionId,p_payload:payload});return result(data,error);}
export async function updateClaimActionStatus(actionId:string,status:string,note?:string){const{data,error}=await supabase.rpc('rpc_update_claim_action_status',{p_action_id:actionId,p_status:status,p_completion_note:note??null});return result(data,error);}
export async function upsertClaimFinancial(id:string,financialId:string|null,payload:Record<string,unknown>){const{data,error}=await supabase.rpc('rpc_upsert_claim_financial',{p_claim_id:id,p_financial_id:financialId,p_payload:payload});return result(data,error);}
export async function recordClaimSettlement(id:string,payload:Record<string,unknown>){const{data,error}=await supabase.rpc('rpc_record_claim_settlement',{p_claim_id:id,p_payload:payload});return result(data,error);}
export async function getClaimFinanceHandoff(id:string){const{data,error}=await supabase.rpc('rpc_get_claim_finance_handoff',{p_claim_id:id});return result<{route:string;accounting_mutated:false}>(data,error);}
export async function listClaimDocuments(id:string){const{data,error}=await supabase.rpc('rpc_list_claim_documents',{p_claim_id:id});return result<DocumentFile[]>(data,error);}
export async function listPartnerClaims(type:'customer'|'provider',id:string){const{data,error}=await supabase.rpc('rpc_list_partner_claims',{p_partner_type:type,p_partner_id:id,p_limit:50});return result<ClaimListItem[]>(data,error);}
export async function getClaimsDashboard(tenantId:string,start?:Date,end?:Date){const{data,error}=await supabase.rpc('rpc_get_claims_dashboard',{p_tenant_id:tenantId,p_from:start?.toISOString()??null,p_to:end?.toISOString()??null});return result<ClaimsDashboard>(data,error);}
export async function listClaimsAttentionItems(tenantId:string){const{data,error}=await supabase.rpc('rpc_list_claim_attention_items',{p_tenant_id:tenantId});const items=result<{items:Array<{kind:string;priority:'critical'|'high'|'medium'|'low';title:string;entity_type:string;entity_id:string;route:string;due_at:string|null}>}>(data,error).items;return items.map((item):AttentionItem=>({...item,severity:item.priority,subtitle:'Claims & Customer Service',reference:item.title.split(' · ')[0],module:'claims',occurred_at:item.due_at??new Date().toISOString()}));}
export async function searchClaims(tenantId:string,query:string){const{data,error}=await supabase.rpc('rpc_search_claims',{p_tenant_id:tenantId,p_query:query,p_limit:10});return result<Array<{id:string;claim_number:string;subject:string;status:string;route:string}>>(data,error);}
export async function getClaimReporting(tenantId:string,start:Date,end:Date){const{data,error}=await supabase.rpc('rpc_get_claim_reporting',{p_tenant_id:tenantId,p_from:start.toISOString(),p_to:end.toISOString()});return result<ClaimReporting>(data,error);}
export async function exportClaims(tenantId:string,filters:Record<string,unknown>){const{data,error}=await supabase.rpc('rpc_export_claims',{p_tenant_id:tenantId,p_filters:filters});return result<Array<Record<string,unknown>>>(data,error);}
