import assert from 'node:assert/strict';import{readFileSync}from'node:fs';
const service=readFileSync(new URL('./compliance.service.ts',import.meta.url),'utf8');
const migration=readFileSync(new URL('../../supabase/migrations/20260829000000_f9_compliance_contracts.sql',import.meta.url),'utf8');
const workspace=readFileSync(new URL('../components/commercial/ComplianceWorkspace.tsx',import.meta.url),'utf8');
const partner=readFileSync(new URL('../components/commercial/PartnerCompliancePanel.tsx',import.meta.url),'utf8');
const partner360=readFileSync(new URL('../components/commercial/Partner360Panel.tsx',import.meta.url),'utf8');
const rates=readFileSync(new URL('../components/commercial/QuoteRateComparison.tsx',import.meta.url),'utf8');
const assignment=readFileSync(new URL('../components/operations/AssignmentDrawer.tsx',import.meta.url),'utf8');
const readiness=readFileSync(new URL('../components/operations/OperationReadiness.tsx',import.meta.url),'utf8');
const dashboard=readFileSync(new URL('../pages/DashboardPage.tsx',import.meta.url),'utf8');
const palette=readFileSync(new URL('../components/productivity/GlobalCommandPalette.tsx',import.meta.url),'utf8');
for(const rpc of['rpc_get_partner_compliance_status','rpc_list_compliance_requirements','rpc_upsert_compliance_requirement','rpc_submit_partner_compliance_record','rpc_review_partner_compliance_record','rpc_waive_partner_requirement','rpc_upsert_partner_contract','rpc_renew_partner_contract','rpc_terminate_partner_contract','rpc_list_compliance_matrix','rpc_list_compliance_expirations','rpc_export_partner_compliance','rpc_get_provider_compliance_badges','rpc_get_compliance_dashboard','rpc_list_compliance_attention_items','rpc_create_provider_compliance_override'])assert.ok(service.includes(rpc),`Missing F9 consumer ${rpc}`);
for(const table of['partner_compliance_requirements','partner_compliance_records','partner_contracts','provider_compliance_overrides'])assert.ok(migration.includes(`CREATE TABLE public.${table}`),`Missing ${table}`);
assert.match(migration,/is_required AND is_blocking AND blocks_operation_assignment/);assert.match(migration,/provider_compliance_blocked/);assert.match(migration,/CREATE OR REPLACE FUNCTION public\.rpc_get_operation_dispatch_readiness\(p_operation_id uuid\)/);
assert.ok(workspace.includes("['summary','Resumen']")&&workspace.includes("['providers','Proveedores']")&&workspace.includes("['customers','Clientes']")&&workspace.includes("['requirements','Requisitos']")&&workspace.includes("['contracts','Contratos']")&&workspace.includes("['expiring','Por vencer']"),'Compliance workspace tabs missing');
assert.ok(partner.includes('DocumentUploader')&&partner.includes('createDocumentSignedUrl')&&partner.includes('Renovar preservando historial'),'F3 document or renewal integration missing');
assert.ok(partner360.includes('["compliance", "Cumplimiento"]')&&partner360.includes('["contracts", "Contratos"]'),'Partner360 compliance tabs missing');
assert.ok(rates.includes('compliance_badge')&&rates.includes('Bloqueado')&&rates.includes('Usar tarifa'),'Rate comparison must warn without hiding/apply blocking');
assert.ok(assignment.includes('getProviderOperationalEligibility')&&assignment.includes('createProviderComplianceOverride')&&readiness.includes('provider_compliance_ready'),'F2 gate/readiness UI missing');
assert.ok(dashboard.includes("role==='admin'&&compliance")&&dashboard.includes('getComplianceDashboard'),'Admin compliance dashboard missing');
assert.ok(palette.includes('searchCompliance')&&palette.includes('/commercial?view=compliance'),'Admin search/action missing');
const financeActions=palette.slice(palette.indexOf('const financeActions'),palette.indexOf('export function'));assert.ok(!financeActions.includes('compliance')&&!financeActions.includes('/commercial'),'Finance palette exposes compliance');
assert.ok(!workspace.match(/bulk.*(accept|reject|waive|override)/i),'Unsafe compliance bulk action exposed');
assert.ok(service.includes('serializeCsv')&&service.includes('downloadCsvContent')&&!service.includes('signed_url'),'F6 CSV safety or URL privacy missing');
