import { useCallback,useEffect,useState,type FormEvent } from 'react';
import { AlertTriangle,CheckCircle2,Clock3,FileCheck2,Loader2,ShieldCheck } from 'lucide-react';
import { DocumentUploader } from '@/components/documents/DocumentUploader';
import { createDocumentSignedUrl,listDocumentFiles } from '@/services/documents.service';
import { activatePartnerContract,getPartnerCompliance,listComplianceRequirements,renewPartnerContract,reviewComplianceRecord,savePartnerContract,submitComplianceRecord,terminatePartnerContract,waivePartnerRequirement } from '@/services/compliance.service';
import type { DocumentFile } from '@/types/documents';
import type { ComplianceRequirement,PartnerComplianceBundle,PartnerType } from '@/types/compliance';
import { listPartnerHistoryPage } from '@/services/rates.service';

const labels={missing:'Faltante',pending_review:'Pendiente',valid:'Vigente',expiring:'Por vencer',expired:'Vencido',rejected:'Rechazado',waived:'Dispensado'} as const;
const tone=(status:string)=>status==='valid'||status==='waived'?'bg-emerald-50 text-emerald-700':status==='expiring'||status==='pending_review'?'bg-amber-50 text-amber-700':status==='missing'||status==='expired'||status==='rejected'?'bg-red-50 text-red-700':'bg-slate-50 text-slate-600';

export function PartnerCompliancePanel({tenantId,entityType,entityId,initialTab='compliance'}:{tenantId:string;entityType:PartnerType;entityId:string;initialTab?:'compliance'|'contracts'}){
 const[data,setData]=useState<PartnerComplianceBundle|null>(null),[requirements,setRequirements]=useState<ComplianceRequirement[]>([]),[files,setFiles]=useState<DocumentFile[]>([]),[tab,setTab]=useState(initialTab),[requirementId,setRequirementId]=useState(''),[fileId,setFileId]=useState(''),[validTo,setValidTo]=useState(''),[busy,setBusy]=useState(true),[error,setError]=useState(''),[contractOpen,setContractOpen]=useState(false);
 const load=useCallback(async()=>{setBusy(true);try{const[bundle,reqs,docs]=await Promise.all([getPartnerCompliance(tenantId,entityType,entityId),listComplianceRequirements(tenantId,{partner_type:entityType,active_only:true}),listDocumentFiles(tenantId,{source_entity_type:entityType,source_entity_id:entityId,limit:100})]);setData(bundle);setRequirements(reqs);setFiles(docs.items);setRequirementId(v=>v||reqs[0]?.id||'');setError('')}catch(e){setError(e instanceof Error?e.message:'No fue posible cargar el cumplimiento.')}finally{setBusy(false)}},[entityId,entityType,tenantId]);
 useEffect(()=>{setData(null);void load()},[load]);if(busy&&!data)return <div className="flex h-32 items-center justify-center"><Loader2 className="animate-spin text-primary"/></div>;if(!data)return <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>;
 const partnerPayload=entityType==='customer'?{customer_id:entityId}:{provider_id:entityId};
 const attach=async(nextFileId=fileId)=>{if(!requirementId||!nextFileId)return;try{await submitComplianceRecord(tenantId,{requirement_id:requirementId,...partnerPayload,document_file_id:nextFileId,valid_to:validTo||null});await load()}catch(e){setError(e instanceof Error?e.message:'No fue posible registrar la evidencia.')}};
 const waive=async(id:string)=>{const until=window.prompt('Dispensa hasta (AAAA-MM-DD)');if(!until)return;const reason=window.prompt('Motivo obligatorio');if(!reason)return;await waivePartnerRequirement(tenantId,{requirement_id:id,...partnerPayload,waiver_until:until,reason});await load()};
 const decide=async(id:string,decision:'accepted'|'rejected')=>{const note=window.prompt(decision==='accepted'?'Nota de revisión (opcional)':'Motivo de rechazo obligatorio')??'';if(decision==='rejected'&&!note)return;await reviewComplianceRecord(id,decision,note);await load()};
 const loadOlder=async(kind:'compliance'|'contracts')=>{const current=kind==='compliance'?data.records_page:data.contracts_page;if(!current?.next_cursor)return;setBusy(true);try{const page=await listPartnerHistoryPage(tenantId,entityType,entityId,kind,current.next_cursor);setData(value=>value?{...value,...(kind==='compliance'?{records:[...value.records,...page.items as unknown as typeof value.records],records_page:page}:{contracts:[...value.contracts,...page.items as unknown as typeof value.contracts],contracts_page:page})}:value)}catch(e){setError(e instanceof Error?e.message:'No fue posible cargar más historial.')}finally{setBusy(false)}};
 return <section className="space-y-4 rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-black uppercase text-primary">Control ROTERO · no certificación legal</p><h3 className="font-black">Cumplimiento y contratos</h3></div><div className={`rounded-full px-3 py-1 text-xs font-black ${tone(data.badge==='current'?'valid':data.badge==='attention'?'expiring':'expired')}`}>{data.badge==='current'?'Vigente':data.badge==='attention'?'Atención':'Bloqueado'}</div></div>
 <div className="grid grid-cols-4 gap-2">{[['Requeridos',data.total_required],['Vigentes',data.valid],['Por vencer',data.expiring],['Bloqueos',data.blocking]].map(([l,v])=><div key={l} className="rounded-xl bg-slate-50 p-3"><b className="text-xl">{v}</b><p className="text-[10px] uppercase text-slate-400">{l}</p></div>)}</div>
 <nav className="flex gap-1"><button onClick={()=>setTab('compliance')} className={`rounded-lg px-3 py-2 text-xs font-bold ${tab==='compliance'?'bg-slate-900 text-white':'bg-slate-50'}`}>Cumplimiento</button><button onClick={()=>setTab('contracts')} className={`rounded-lg px-3 py-2 text-xs font-bold ${tab==='contracts'?'bg-slate-900 text-white':'bg-slate-50'}`}>Contratos</button></nav>
 {error&&<p className="rounded-lg bg-red-50 p-2 text-xs text-red-700">{error}</p>}
 {tab==='compliance'&&<><div className="space-y-2">{data.requirements.map(r=><div key={r.id} className="rounded-xl border p-3"><div className="flex flex-wrap items-center gap-2"><b className="flex-1 text-sm">{r.name}</b>{r.assignment_blocker&&<span title="Bloquea asignación configurada"><AlertTriangle size={14} className="text-red-600"/></span>}<span className={`rounded-full px-2 py-1 text-[10px] font-black ${tone(r.derived_status)}`}>{labels[r.derived_status]}</span></div><p className="mt-1 text-[11px] text-slate-400">{r.category} · aviso {r.warning_days}d {r.valid_to?`· vence ${r.valid_to}`:''}</p><div className="mt-2 flex gap-2">{r.record_id&&r.review_status==='pending'&&<><button onClick={()=>void decide(r.record_id!,'accepted')} className="text-xs font-bold text-emerald-700">Aceptar</button><button onClick={()=>void decide(r.record_id!,'rejected')} className="text-xs font-bold text-red-700">Rechazar</button></>} {['missing','expired','rejected','pending_review'].includes(r.derived_status)&&<button onClick={()=>void waive(r.id)} className="text-xs font-bold text-amber-700">Dispensa temporal</button>}</div></div>)}</div>
 <div className="rounded-xl border p-3"><h4 className="text-xs font-black uppercase text-slate-500">Nueva evidencia privada</h4><div className="my-3 grid gap-2 md:grid-cols-3"><select value={requirementId} onChange={e=>setRequirementId(e.target.value)} className="rounded-lg border p-2 text-xs">{requirements.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><input type="date" value={validTo} onChange={e=>setValidTo(e.target.value)} className="rounded-lg border p-2 text-xs" title="Vigente hasta"/><div className="flex gap-1"><select value={fileId} onChange={e=>setFileId(e.target.value)} className="min-w-0 flex-1 rounded-lg border p-2 text-xs"><option value="">Documento existente</option>{files.map(f=><option key={f.id} value={f.id}>{f.file_name}</option>)}</select><button disabled={!fileId} onClick={()=>void attach()} className="rounded-lg bg-slate-900 px-3 text-xs font-bold text-white disabled:opacity-40">Usar</button></div></div><DocumentUploader tenantId={tenantId} sourceModule="commercial" entityType={entityType} entityId={entityId} fileKind="provider_upload" compact onUploaded={async file=>{setFiles(v=>[file,...v]);setFileId(file.id);await attach(file.id)}}/></div>
 <div className="space-y-2"><h4 className="text-xs font-black uppercase text-slate-500">Historial preservado</h4>{data.records.map(r=><button key={r.id} onClick={()=>{const f=files.find(x=>x.id===r.document_file_id);if(f)void createDocumentSignedUrl(f,false).then(url=>window.open(url,'_blank','noopener,noreferrer'))}} className="flex w-full items-center gap-2 rounded-lg bg-slate-50 p-2 text-left text-xs"><FileCheck2 size={14}/><span className="flex-1">{r.requirement_name} · {r.file_name||'Dispensa sin archivo'}</span><span>{(r.created_at??(r as unknown as{sort_at:string}).sort_at).slice(0,10)}</span></button>)}{data.records_page?.has_more&&<button type="button" disabled={busy} onClick={()=>void loadOlder('compliance')} className="w-full rounded-lg border p-2 text-xs font-bold">{busy?'Cargando…':'Cargar evidencia anterior'}</button>}</div></>}
 {tab==='contracts'&&<><button onClick={()=>setContractOpen(true)} className="rounded-lg bg-primary px-3 py-2 text-xs font-black text-white">Nuevo contrato</button><div className="space-y-2">{data.contracts.map(c=><div key={c.id} className="rounded-xl border p-3"><div className="flex items-center gap-2"><ShieldCheck size={15} className="text-primary"/><b className="flex-1">{c.title}</b><span className={`rounded-full px-2 py-1 text-[10px] font-black ${tone(c.derived_status==='active'?'valid':c.derived_status==='expiring'?'expiring':'expired')}`}>{c.derived_status}</span></div><p className="text-xs text-slate-400">{c.reference||'Sin referencia'} · {c.starts_on||'sin inicio'} → {c.ends_on||'sin vencimiento'}</p><div className="mt-2 flex gap-3 text-xs font-bold">{c.status==='draft'&&<button onClick={()=>void activatePartnerContract(c.id).then(load)} className="text-emerald-700">Activar</button>}{c.status==='active'&&<><button onClick={()=>{const starts=window.prompt('Inicio de renovación (AAAA-MM-DD)');if(starts)void renewPartnerContract(c.id,{starts_on:starts,title:c.title,contract_type:c.contract_type,document_file_id:c.document_file_id??null}).then(load)}} className="text-primary">Renovar preservando historial</button><button onClick={()=>{const reason=window.prompt('Motivo de terminación');if(reason)void terminatePartnerContract(c.id,reason).then(load)}} className="text-red-700">Terminar</button></>}</div></div>)}{data.contracts_page?.has_more&&<button type="button" disabled={busy} onClick={()=>void loadOlder('contracts')} className="w-full rounded-lg border p-2 text-xs font-bold">{busy?'Cargando…':'Cargar contratos anteriores'}</button>}</div>{contractOpen&&<ContractForm tenantId={tenantId} partnerPayload={partnerPayload} files={files} onClose={()=>setContractOpen(false)} onSaved={async()=>{setContractOpen(false);await load()}}/>}</>}
 </section>;
}

function ContractForm({tenantId,partnerPayload,files,onClose,onSaved}:{tenantId:string;partnerPayload:Record<string,string>;files:DocumentFile[];onClose:()=>void;onSaved:()=>Promise<void>}){const[form,setForm]=useState({contract_type:'commercial',title:'',reference:'',starts_on:'',ends_on:'',notice_days:30,document_file_id:''});const submit=async(e:FormEvent)=>{e.preventDefault();await savePartnerContract(tenantId,null,{...partnerPayload,...form,document_file_id:form.document_file_id||null});await onSaved()};return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><form onSubmit={submit} className="w-full max-w-xl space-y-3 rounded-2xl bg-white p-6"><h3 className="font-black">Nuevo contrato</h3><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Título" className="w-full rounded-xl border p-3 text-sm"/><div className="grid gap-2 md:grid-cols-2"><input value={form.contract_type} onChange={e=>setForm({...form,contract_type:e.target.value})} placeholder="Tipo" className="rounded-xl border p-3 text-sm"/><input value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})} placeholder="Referencia" className="rounded-xl border p-3 text-sm"/><input type="date" value={form.starts_on} onChange={e=>setForm({...form,starts_on:e.target.value})} className="rounded-xl border p-3 text-sm"/><input type="date" value={form.ends_on} onChange={e=>setForm({...form,ends_on:e.target.value})} className="rounded-xl border p-3 text-sm"/></div><select value={form.document_file_id} onChange={e=>setForm({...form,document_file_id:e.target.value})} className="w-full rounded-xl border p-3 text-sm"><option value="">Documento privado opcional</option>{files.map(f=><option key={f.id} value={f.id}>{f.file_name}</option>)}</select><div className="flex justify-end gap-2"><button type="button" onClick={onClose} className="p-2 text-sm font-bold">Cancelar</button><button className="rounded-xl bg-primary px-4 py-2 text-sm font-black text-white">Guardar borrador</button></div></form></div>}
