import type { DocumentFile } from '@/types/documents';

export type ClaimType = 'delay'|'damage'|'shortage'|'loss'|'documentation'|'billing'|'service_quality'|'provider_performance'|'compliance'|'other';
export type ClaimPriority = 'critical'|'high'|'medium'|'low';
export type ClaimStatus = 'open'|'triage'|'investigating'|'awaiting_customer'|'awaiting_provider'|'action_in_progress'|'resolved'|'closed'|'cancelled';

export interface ClaimListItem { id:string;claim_number:string;claim_type:ClaimType;priority:ClaimPriority;status:ClaimStatus;subject:string;reported_at:string;response_due_at:string|null;resolution_due_at:string|null;updated_at:string;customer_name?:string|null;provider_name?:string|null;operation_reference?:string|null;responsibility?:string;exposure_by_currency?:CurrencyAmount[];sla:{first_response_overdue:boolean;resolution_overdue:boolean}; }
export interface ClaimEvent { id:string;event_type:string;summary:string;metadata:Record<string,unknown>;occurred_at:string; }
export interface ClaimAction { id:string;title:string;owner_user_id:string|null;due_at:string|null;status:'open'|'in_progress'|'done'|'cancelled';completion_note?:string|null; }
export interface ClaimFinancial { id:string;exposure_type:string;amount:number;currency:'MXN'|'USD';status:string;note?:string|null;finance_reference?:string|null; }
export interface ClaimContact { id:string;party:'customer'|'provider';contact_name:string;channel:string;occurred_at:string;summary:string; }
export interface CurrencyAmount { currency:'MXN'|'USD';amount:number; }
export interface Claim360 extends ClaimListItem { description:string;responsible_user_id:string|null;responsibility:string;responsibility_note?:string|null;root_cause:string;root_cause_note?:string|null;resolution_summary?:string|null;first_responded_at:string|null;settlement_amount?:number|null;settlement_currency?:'MXN'|'USD'|null;settlement_type?:string|null;settlement_date?:string|null;settlement_notes?:string|null;customer?:{id:string;display_name:string}|null;provider?:{id:string;display_name:string}|null;operation?:Record<string,unknown>|null;quote?:Record<string,unknown>|null;rate_snapshot?:Record<string,unknown>|null;source_incident?:Record<string,unknown>|null;compliance_requirement?:Record<string,unknown>|null;partner_contract?:Record<string,unknown>|null;events:ClaimEvent[];actions:ClaimAction[];financials:ClaimFinancial[];exposure_by_currency:CurrencyAmount[];contacts:ClaimContact[];available_contacts:Array<{id:string;party:'customer'|'provider';name:string;email?:string|null;phone?:string|null}>;available_responsibles:Array<{id:string;label:string}>;documents:DocumentFile[]; }
export interface ClaimReferenceData { operations:Array<{id:string;reference_code:string;customer_id?:string;provider_id?:string}>;customers:Array<{id:string;display_name:string}>;providers:Array<{id:string;display_name:string}>;members:Array<{user_id:string;email?:string}>; }
export interface ClaimsDashboard { open_count:number;critical_open:number;first_response_overdue:number;resolution_overdue:number;opened_in_period:number;resolved_in_period:number;exposure_by_currency:CurrencyAmount[];by_type:Array<{claim_type:ClaimType;count:number}>; }
export interface ClaimReporting { root_causes:Array<{root_cause:string;total:number}>;provider_recurrence:Array<{provider_id:string;provider_name:string;total:number}>;response_sla:{met:number;breached:number};resolution_sla:{met:number;breached:number}; }
