export type PartnerType = 'customer' | 'provider';
export type ComplianceDerivedStatus = 'missing' | 'pending_review' | 'valid' | 'expiring' | 'expired' | 'rejected' | 'waived';
export interface ComplianceRequirement { id:string;tenant_id:string;code:string;name:string;description?:string;partner_type:PartnerType|'both';category:'tax'|'contract'|'insurance'|'operational'|'banking'|'identity'|'other';is_required:boolean;has_expiration:boolean;warning_days:number;is_blocking:boolean;blocks_operation_assignment:boolean;is_active:boolean;sort_order:number }
export interface ComplianceRequirementStatus extends ComplianceRequirement { record_id?:string;document_file_id?:string;review_status?:'pending'|'accepted'|'rejected'|'waived';valid_from?:string;valid_to?:string;waiver_until?:string;review_note?:string;derived_status:ComplianceDerivedStatus;assignment_blocker:boolean }
export interface ComplianceSummary { total_required:number;valid:number;missing:number;pending:number;expiring:number;expired:number;rejected:number;waived:number;blocking:number;provider_compliance_ready:boolean;badge:'current'|'attention'|'blocked';partner_type:PartnerType;partner_id:string;requirements:ComplianceRequirementStatus[] }
export interface ComplianceRecord { id:string;requirement_id:string;requirement_name:string;document_file_id?:string;file_name?:string;review_status:'pending'|'accepted'|'rejected'|'waived';derived_status:ComplianceDerivedStatus;valid_from?:string;valid_to?:string;waiver_until?:string;review_note?:string;created_at:string }
export interface PartnerContract { id:string;contract_type:string;title:string;reference?:string;document_file_id?:string;file_name?:string;responsible_contact_id?:string;starts_on?:string;ends_on?:string;notice_days:number;status:'draft'|'active'|'terminated'|'archived';derived_status:'draft'|'active'|'expiring'|'expired'|'terminated'|'archived';renewed_from_id?:string;notes?:string;created_at:string }
import type { PartnerHistoryPage } from '@/types/rates';
export interface PartnerComplianceBundle extends ComplianceSummary { records:ComplianceRecord[];contracts:PartnerContract[];records_page?:PartnerHistoryPage;contracts_page?:PartnerHistoryPage;business_date?:string;timezone?:string }
export interface ComplianceMatrixRow extends ComplianceSummary { partner_name:string;is_active:boolean }
export interface ComplianceExpiration { source:'Documento'|'Contrato'|'Tarifa BUY'|'Tarifa SELL';id:string;partner_type:PartnerType;partner_id:string;partner_name:string;title:string;reference?:string;expires_on:string;route:string }
export interface ProviderComplianceBadge { provider_id:string;badge:'current'|'attention'|'blocked';blocking:number;reasons:Array<{code:string;name:string;status:ComplianceDerivedStatus}> }
export interface ComplianceDashboard { blocked_providers:number;missing_required_docs:number;documents_expiring_30d:number;contracts_expiring_30d:number;rates_expiring_30d:number }
