import { AlertTriangle, Bell, CheckCheck, FileText, RefreshCw, Wallet, X } from 'lucide-react';
import { useCallback, useEffect, useRef, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { dismissInternalNotification, listInternalNotifications, markInternalNotificationsRead, refreshInternalNotifications } from '@/services/executive.service';
import type { InternalNotification } from '@/types/executive';

const icons={operations:AlertTriangle,commercial:FileText,documents:FileText,finance:Wallet} as const;

export function NotificationCenter({ tenantId }: { tenantId:string|null }) {
    const navigate=useNavigate(); const {pathname}=useLocation(); const [open,setOpen]=useState(false); const [items,setItems]=useState<InternalNotification[]>([]); const [unread,setUnread]=useState(0); const [loading,setLoading]=useState(false); const ref=useRef<HTMLDivElement>(null);
    const load=useCallback(async(refresh=true)=>{if(!tenantId)return;setLoading(true);try{if(refresh)await refreshInternalNotifications(tenantId);const feed=await listInternalNotifications(tenantId);setItems(feed.items);setUnread(feed.unread_count);}finally{setLoading(false);}},[tenantId]);
    useEffect(()=>{void load(true);},[load,pathname]);
    useEffect(()=>{const onFocus=()=>void load(true);window.addEventListener('focus',onFocus);return()=>window.removeEventListener('focus',onFocus);},[load]);
    useEffect(()=>{const close=(event:MouseEvent)=>{if(ref.current&&!ref.current.contains(event.target as Node))setOpen(false);};document.addEventListener('mousedown',close);return()=>document.removeEventListener('mousedown',close);},[]);
    const openItem=async(item:InternalNotification)=>{if(!tenantId)return;if(!item.read_at)await markInternalNotificationsRead(tenantId,[item.id]);setOpen(false);navigate(item.route);};
    const markAll=async()=>{if(!tenantId)return;await markInternalNotificationsRead(tenantId,null);await load(false);};
    const dismiss=async(id:string)=>{if(!tenantId)return;await dismissInternalNotification(tenantId,id);await load(false);};
    return <div className="relative" ref={ref}><button onClick={()=>setOpen(v=>!v)} className="relative rounded-xl p-2 text-slate-400 hover:bg-primary-50 hover:text-primary" aria-label="Abrir notificaciones"><Bell size={19}/>{unread>0&&<span className="absolute right-0 top-0 flex min-w-4 items-center justify-center rounded-full bg-red-500 px-1 text-[9px] font-black text-white">{Math.min(unread,99)}</span>}</button>{open&&<div className="absolute right-0 top-full z-50 mt-2 w-[min(92vw,380px)] overflow-hidden rounded-2xl border bg-white shadow-2xl"><header className="flex items-center justify-between border-b px-4 py-3"><div><b className="text-sm text-slate-800">Notificaciones</b><p className="text-[10px] text-slate-400">{unread} sin leer</p></div><div className="flex gap-1"><button onClick={()=>void load(true)} title="Actualizar" className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><RefreshCw size={14} className={loading?'animate-spin':''}/></button>{unread>0&&<button onClick={()=>void markAll()} title="Marcar todas leídas" className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><CheckCheck size={15}/></button>}</div></header><div className="max-h-[440px] divide-y overflow-y-auto">{items.length===0?<div className="p-10 text-center text-xs text-slate-400">Sin notificaciones relevantes.</div>:items.map(item=>{const Icon=icons[item.module];return <div key={item.id} className={`group flex items-start gap-3 p-4 ${item.read_at?'bg-white':'bg-blue-50/40'}`}><button onClick={()=>void openItem(item)} className="flex min-w-0 flex-1 items-start gap-3 text-left"><span className="rounded-lg bg-slate-100 p-2 text-slate-600"><Icon size={14}/></span><span className="min-w-0"><span className="block truncate text-xs font-black text-slate-800">{item.title}</span><span className="mt-0.5 block text-[11px] leading-relaxed text-slate-500">{item.body}</span><span className="mt-1 block text-[9px] font-bold uppercase text-slate-300">{item.priority} · {new Date(item.occurred_at).toLocaleString('es-MX')}</span></span></button><button onClick={()=>void dismiss(item.id)} title="Descartar" className="p-1 text-slate-300 opacity-0 hover:text-red-500 group-hover:opacity-100"><X size={13}/></button></div>})}</div></div>}</div>;
}
