import { Bookmark, Check, Pencil, Star, Trash2 } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { deleteSavedView, listSavedViews, saveView } from '@/services/executive.service';
import type { ProductivityModule, SavedView } from '@/types/executive';

export function SavedViewsMenu({ tenantId,module,filters,onApply }: { tenantId:string|null; module:ProductivityModule; filters:Record<string,unknown>; onApply:(filters:Record<string,unknown>)=>void }) {
    const [open,setOpen]=useState(false); const [views,setViews]=useState<SavedView[]>([]); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
    const load=useCallback(async()=>{if(!tenantId)return;try{setViews(await listSavedViews(tenantId,module));}catch(cause){setError(cause instanceof Error?cause.message:'No fue posible cargar vistas.');}},[tenantId,module]);
    useEffect(()=>{void load();},[load]);
    const create=async()=>{if(!tenantId)return;const name=window.prompt('Nombre de la vista');if(!name?.trim())return;setBusy(true);setError(null);try{await saveView(tenantId,{module,name:name.trim(),filters,is_default:views.length===0});await load();setOpen(true);}catch(cause){setError(cause instanceof Error?cause.message:'No fue posible guardar la vista.');}finally{setBusy(false);}};
    const rename=async(view:SavedView)=>{if(!tenantId)return;const name=window.prompt('Nuevo nombre',view.name);if(!name?.trim())return;await saveView(tenantId,{...view,name:name.trim()});await load();};
    const makeDefault=async(view:SavedView)=>{if(!tenantId)return;await saveView(tenantId,{...view,is_default:true});await load();};
    const remove=async(view:SavedView)=>{if(!tenantId||!window.confirm(`Eliminar la vista “${view.name}”?`))return;await deleteSavedView(tenantId,view.id,module);await load();};
    return <div className="relative"><button type="button" disabled={!tenantId||busy} onClick={()=>setOpen(v=>!v)} className="inline-flex items-center gap-2 rounded-xl border bg-white px-3 py-2 text-xs font-bold text-slate-600 disabled:opacity-50"><Bookmark size={14}/>Vistas guardadas</button>{open&&<div className="absolute right-0 z-30 mt-2 w-72 overflow-hidden rounded-xl border bg-white shadow-2xl"><div className="flex items-center justify-between border-b px-3 py-2"><b className="text-xs text-slate-700">{module}</b><button onClick={()=>void create()} className="text-[10px] font-black uppercase text-primary">Guardar actual</button></div>{error&&<p className="p-3 text-xs text-red-600">{error}</p>}<div className="max-h-64 overflow-y-auto">{views.length===0?<p className="p-5 text-center text-xs text-slate-400">Aún no hay vistas.</p>:views.map(view=><div key={view.id} className="flex items-center gap-1 border-b p-2 last:border-0"><button onClick={()=>{onApply(view.filters);setOpen(false);}} className="min-w-0 flex-1 rounded-lg px-2 py-2 text-left hover:bg-slate-50"><span className="flex items-center gap-1 text-xs font-bold text-slate-700">{view.is_default&&<Check size={12} className="text-emerald-600"/>}{view.name}</span></button><button onClick={()=>void makeDefault(view)} title="Predeterminada" className="p-1.5 text-slate-300 hover:text-amber-500"><Star size={13}/></button><button onClick={()=>void rename(view)} title="Renombrar" className="p-1.5 text-slate-300 hover:text-primary"><Pencil size={13}/></button><button onClick={()=>void remove(view)} title="Eliminar" className="p-1.5 text-slate-300 hover:text-red-500"><Trash2 size={13}/></button></div>)}</div></div>}</div>;
}
