import { useState } from 'react';
import { Download, Loader2 } from 'lucide-react';
import { exportData } from '@/services/dataOperations.service';
import { downloadCsvContent, serializeCsv } from '@/utils/csv';
import { EXPORT_ENTITY_LABELS, type ExportEntity } from '@/types/dataOperations';

export function ExportCenter({ tenantId }: { tenantId: string }) {
    const [entity, setEntity] = useState<ExportEntity>('operations'); const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [dateFrom, setDateFrom] = useState(''); const [dateTo, setDateTo] = useState('');
    const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [lastCount, setLastCount] = useState<number | null>(null);
    const run = async () => { setBusy(true); setError(null); try { const rows = await exportData(tenantId, entity, { search: search || undefined, status: status || undefined, date_from: dateFrom || undefined, date_to: dateTo || undefined }); if (!rows.length) throw new Error('No hay filas para exportar con estos filtros.'); downloadCsvContent(serializeCsv(rows), `rotero-${entity}-${new Date().toISOString().slice(0, 10)}.csv`); setLastCount(rows.length); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No fue posible exportar.'); } finally { setBusy(false); } };
    return <section className="rounded-2xl border bg-white p-5"><h2 className="text-lg font-bold">Centro de exportación</h2><p className="mb-5 text-xs text-slate-500">Exportación paginada y auditada. Máximo síncrono: 5,000 filas. Las celdas se neutralizan para Excel.</p><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-5"><label className="text-xs font-bold text-slate-500">Conjunto<select value={entity} onChange={(event) => setEntity(event.target.value as ExportEntity)} className="mt-1 w-full rounded-xl border px-3 py-2 text-slate-700">{(Object.keys(EXPORT_ENTITY_LABELS) as ExportEntity[]).map((value) => <option key={value} value={value}>{EXPORT_ENTITY_LABELS[value]}</option>)}</select></label><label className="text-xs font-bold text-slate-500">Buscar<input value={search} onChange={(event) => setSearch(event.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2" /></label><label className="text-xs font-bold text-slate-500">Estado<input value={status} onChange={(event) => setStatus(event.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2" /></label><label className="text-xs font-bold text-slate-500">Desde<input type="date" value={dateFrom} onChange={(event) => setDateFrom(event.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2" /></label><label className="text-xs font-bold text-slate-500">Hasta<input type="date" value={dateTo} onChange={(event) => setDateTo(event.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2" /></label></div>{error && <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{lastCount !== null && <p className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">Se descargaron {lastCount.toLocaleString('es-MX')} filas.</p>}<button disabled={busy} onClick={() => void run()} className="mt-5 flex items-center gap-2 rounded-xl bg-primary px-5 py-2.5 text-xs font-bold text-white disabled:opacity-50">{busy ? <Loader2 size={15} className="animate-spin" /> : <Download size={15} />}Exportar CSV</button></section>;
}
