import { useCallback, useEffect, useState } from 'react';
import { Loader2, RefreshCw } from 'lucide-react';
import { listImportBatches } from '@/services/dataOperations.service';
import { IMPORT_ENTITY_LABELS, type ImportBatch } from '@/types/dataOperations';

export function ImportHistory({ tenantId }: { tenantId: string }) {
    const [items, setItems] = useState<ImportBatch[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
    const load = useCallback(async () => { setLoading(true); setError(null); try { setItems(await listImportBatches(tenantId)); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No se pudo cargar el historial.'); } finally { setLoading(false); } }, [tenantId]);
    useEffect(() => { void load(); }, [load]);
    return <section className="rounded-2xl border bg-white p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-lg font-bold">Historial de importaciones</h2><p className="text-xs text-slate-500">Metadatos, conteos e idempotencia; nunca el cuerpo del CSV.</p></div><button onClick={() => void load()} className="rounded-xl border p-2"><RefreshCw size={15} /></button></div>{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{loading ? <Loader2 className="animate-spin text-primary" /> : !items.length ? <p className="rounded-xl border border-dashed p-10 text-center text-sm text-slate-400">Aún no hay importaciones confirmadas.</p> : <div className="overflow-x-auto rounded-xl border"><table className="min-w-full text-left text-xs"><thead className="bg-slate-50 text-slate-400"><tr>{['Fecha','Entidad','Archivo','Modo','Estado','Creadas','Actualizadas','Errores'].map((label) => <th key={label} className="px-3 py-3">{label}</th>)}</tr></thead><tbody className="divide-y">{items.map((item) => <tr key={item.id}><td className="px-3 py-3">{new Date(item.started_at).toLocaleString('es-MX')}</td><td className="px-3 py-3 font-bold">{IMPORT_ENTITY_LABELS[item.entity_type]}</td><td className="max-w-52 truncate px-3 py-3" title={item.filename}>{item.filename}</td><td className="px-3 py-3">{item.mode}</td><td className="px-3 py-3">{item.status}</td><td className="px-3 py-3">{item.applied_rows}</td><td className="px-3 py-3">{item.updated_rows}</td><td className="px-3 py-3 text-red-600">{item.error_rows}</td></tr>)}</tbody></table></div>}</section>;
}
