import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { AnimatePresence, motion } from 'motion/react';
import { AlertCircle, Calendar, Loader2, Truck, UserRound, X } from 'lucide-react';
import { listProviders } from '@/services/commercial.service';
import { assignOperation } from '@/services/operations.service';
import { createProviderComplianceOverride, getProviderOperationalEligibility } from '@/services/compliance.service';
import { useAuthStore } from '@/store/authStore';
import type { LogisticsProvider } from '@/types/commercial';
import type { Operation, OperationPriority } from '@/types/operations';

export function AssignmentDrawer({ isOpen, onClose, operation, onAssigned }: { isOpen: boolean; onClose: () => void; operation: Operation | null; onAssigned: () => void }) {
    const activeTenant = useAuthStore((state) => state.activeTenant);
    const role = useAuthStore((state) => state.getRole());
    const [providers, setProviders] = useState<LogisticsProvider[]>([]);
    const [providerId, setProviderId] = useState(''); const [driverName, setDriverName] = useState(''); const [driverPhone, setDriverPhone] = useState('');
    const [vehicleRef, setVehicleRef] = useState(''); const [vehiclePlates, setVehiclePlates] = useState('');
    const [plannedDeparture, setPlannedDeparture] = useState(''); const [priority, setPriority] = useState<OperationPriority>('normal'); const [reason, setReason] = useState('');
    const [loadingProviders, setLoadingProviders] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
    const [eligibility,setEligibility]=useState<{eligible:boolean;badge:string;reasons:Array<{name:string;status:string}>}|null>(null); const [complianceOverride,setComplianceOverride]=useState(false);
    const selectedProvider = useMemo(() => providers.find((item) => item.id === providerId), [providerId, providers]);

    useEffect(() => { if (!isOpen || !activeTenant) return; setLoadingProviders(true); listProviders(activeTenant, { active: true }).then(setProviders).catch(() => setError('No fue posible cargar la red de proveedores.')).finally(() => setLoadingProviders(false)); }, [activeTenant, isOpen]);
    useEffect(() => { if (!operation || !isOpen) return; const externalDriver = operation.external_driver ?? {}; const externalVehicle = operation.external_vehicle ?? {}; setProviderId(operation.provider_id || ''); setDriverName(typeof externalDriver.name === 'string' ? externalDriver.name : ''); setDriverPhone(typeof externalDriver.phone === 'string' ? externalDriver.phone : ''); setVehicleRef(typeof externalVehicle.reference === 'string' ? externalVehicle.reference : typeof externalVehicle.unit_code === 'string' ? externalVehicle.unit_code : ''); setVehiclePlates(typeof externalVehicle.plates === 'string' ? externalVehicle.plates : ''); setPlannedDeparture(operation.planned_departure ? new Date(new Date(operation.planned_departure).getTime() - new Date(operation.planned_departure).getTimezoneOffset() * 60000).toISOString().slice(0,16) : ''); setPriority((operation.priority as OperationPriority) || 'normal'); setReason(''); setError(null); }, [isOpen, operation]);
    useEffect(()=>{if(!activeTenant||!providerId){setEligibility(null);return;}let active=true;getProviderOperationalEligibility(activeTenant,providerId).then(value=>{if(active)setEligibility(value)}).catch(()=>{if(active)setEligibility(null)});return()=>{active=false}},[activeTenant,providerId]);
    const submit = async (event: FormEvent) => { event.preventDefault(); if (!activeTenant || !operation?.db_id || !selectedProvider) return; if (operation.assigned_at && reason.trim().length < 5) return setError('Describe el motivo del cambio de asignación.'); if(eligibility&&!eligibility.eligible&&(!complianceOverride||role!=='admin'))return setError('El proveedor tiene bloqueos configurados. Sólo Admin puede registrar un override específico.');if(eligibility&&!eligibility.eligible&&reason.trim().length<5)return setError('El override Admin requiere un motivo de al menos 5 caracteres.'); setSaving(true); setError(null); try { if(eligibility&&!eligibility.eligible)await createProviderComplianceOverride(operation.db_id,selectedProvider.id,reason.trim());await assignOperation(activeTenant, operation.db_id, { execution_type: 'third_party', provider_id: selectedProvider.id, provider_name: selectedProvider.display_name, external_driver: { ...(driverName.trim() ? { name: driverName.trim() } : {}), ...(driverPhone.trim() ? { phone: driverPhone.trim() } : {}) }, external_vehicle: { ...(vehicleRef.trim() ? { reference: vehicleRef.trim() } : {}), ...(vehiclePlates.trim() ? { plates: vehiclePlates.trim() } : {}) }, planned_departure: new Date(plannedDeparture).toISOString(), priority, reason: reason.trim() || undefined }); onAssigned(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No fue posible guardar la asignación.'); } finally { setSaving(false); } };

    return <AnimatePresence>{isOpen && operation && <div className="fixed inset-0 z-50 bg-slate-950/40 backdrop-blur-sm"><motion.button type="button" aria-label="Cerrar asignación" className="absolute inset-0" onClick={onClose} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} /><motion.aside initial={{ x: 520 }} animate={{ x: 0 }} exit={{ x: 520 }} className="absolute inset-y-0 right-0 flex w-full max-w-lg flex-col bg-white shadow-2xl"><header className="flex items-center justify-between border-b border-slate-200 px-6 py-4"><div><h2 className="text-lg font-black text-slate-800">Asignación contratada</h2><p className="text-xs text-slate-400">{operation.id} · third-party primero</p></div><button onClick={onClose} className="rounded-lg bg-slate-100 p-2 text-slate-500"><X size={17} /></button></header><form onSubmit={submit} className="flex-1 space-y-5 overflow-y-auto p-6">
        <div className="rounded-xl border border-sky-200 bg-sky-50 p-3 text-xs text-sky-800">El proveedor no recibe acceso ERP. Chofer y unidad externos se guardan como snapshots opcionales.</div>
        {error && <div className="flex gap-2 rounded-xl border border-red-200 bg-red-50 p-3 text-xs font-semibold text-red-700"><AlertCircle size={15} />{error}</div>}
        <label className="block text-xs font-bold uppercase tracking-wider text-slate-500"><span className="flex items-center gap-2"><Truck size={14} />Proveedor contratado</span><select required disabled={loadingProviders} value={providerId} onChange={(e) => setProviderId(e.target.value)} className="mt-2 w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm font-normal"><option value="">{loadingProviders ? 'Cargando…' : 'Seleccionar proveedor'}</option>{providers.map((item) => <option key={item.id} value={item.id}>{item.display_name}</option>)}</select></label>
        {eligibility&&<div className={`rounded-xl border p-3 text-xs ${eligibility.eligible?'border-emerald-200 bg-emerald-50 text-emerald-800':'border-red-200 bg-red-50 text-red-800'}`}><b>{eligibility.eligible?'Proveedor vigente para asignación':'Proveedor bloqueado por política configurada'}</b>{eligibility.reasons.length>0&&<p className="mt-1">{eligibility.reasons.map(item=>`${item.name}: ${item.status}`).join(' · ')}</p>}{!eligibility.eligible&&role==='admin'&&<label className="mt-2 flex items-center gap-2 font-bold"><input type="checkbox" checked={complianceOverride} onChange={e=>setComplianceOverride(e.target.checked)}/>Override sólo para esta operación/proveedor</label>}</div>}
        <div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold uppercase tracking-wider text-slate-500"><span className="flex items-center gap-2"><UserRound size={14} />Chofer del proveedor</span><input value={driverName} onChange={(e) => setDriverName(e.target.value)} placeholder="Opcional" className="mt-2 w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm font-normal normal-case" /></label><label className="text-xs font-bold uppercase tracking-wider text-slate-500">Teléfono<input value={driverPhone} onChange={(e) => setDriverPhone(e.target.value)} placeholder="Opcional" className="mt-2 w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm font-normal normal-case" /></label><label className="text-xs font-bold uppercase tracking-wider text-slate-500">Unidad / referencia<input value={vehicleRef} onChange={(e) => setVehicleRef(e.target.value)} placeholder="Opcional" className="mt-2 w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm font-normal normal-case" /></label><label className="text-xs font-bold uppercase tracking-wider text-slate-500">Placas<input value={vehiclePlates} onChange={(e) => setVehiclePlates(e.target.value)} placeholder="Opcional" className="mt-2 w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm font-normal normal-case" /></label></div>
        <label className="block text-xs font-bold uppercase tracking-wider text-slate-500"><span className="flex items-center gap-2"><Calendar size={14} />Salida planeada</span><input required type="datetime-local" value={plannedDeparture} onChange={(e) => setPlannedDeparture(e.target.value)} className="mt-2 w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm font-normal" /></label>
        <div><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Prioridad</p><div className="mt-2 grid grid-cols-3 gap-2">{(['low','normal','high'] as OperationPriority[]).map((value) => <button key={value} type="button" onClick={() => setPriority(value)} className={`rounded-lg border py-2 text-xs font-bold ${priority === value ? 'border-primary bg-primary/5 text-primary' : 'border-slate-200 text-slate-500'}`}>{value === 'low' ? 'Baja' : value === 'high' ? 'Alta' : 'Normal'}</button>)}</div></div>
        <label className="block text-xs font-bold uppercase tracking-wider text-slate-500">Motivo del cambio<input required={Boolean(operation.assigned_at)} minLength={operation.assigned_at ? 5 : undefined} value={reason} onChange={(e) => setReason(e.target.value)} placeholder={operation.assigned_at ? 'Obligatorio para reasignar' : 'Opcional en asignación inicial'} className="mt-2 w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm font-normal normal-case" /></label>
        <div className="flex gap-3 border-t border-slate-100 pt-4"><button type="button" onClick={onClose} className="flex-1 rounded-xl bg-slate-100 py-2.5 text-sm font-bold text-slate-600">Cancelar</button><button disabled={saving || !providerId || !plannedDeparture} className="flex-[2] inline-flex items-center justify-center gap-2 rounded-xl bg-primary py-2.5 text-sm font-bold text-white disabled:opacity-50">{saving && <Loader2 size={16} className="animate-spin" />}Guardar asignación</button></div>
    </form></motion.aside></div>}</AnimatePresence>;
}
