import { useState, type FormEvent } from 'react';
import { ExternalLink, FileText, Loader2, Plus } from 'lucide-react';
import { addOperationEvidence } from '@/services/operations.service';
import type { EvidenceKind, Operation360Data } from '@/types/operations';
import { formatOperationDate } from './operationsControl';

export function OperationEvidence({ data, canManage, onRefresh }: { data: Operation360Data; canManage: boolean; onRefresh: () => Promise<void> }) {
    const [formOpen, setFormOpen] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
    const [form, setForm] = useState({ kind: 'operational_note' as EvidenceKind, note: '', reference: '', url: '', incident: '' });
    const submit = async (event: FormEvent) => { event.preventDefault(); if (!data.operation.db_id) return; setSaving(true); setError(null); try { await addOperationEvidence(data.operation.db_id, { kind: form.kind, note: form.note, file_ref: form.reference, external_url: form.url, incident_id: form.incident || null }); setForm({ kind: 'operational_note', note: '', reference: '', url: '', incident: '' }); setFormOpen(false); await onRefresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No fue posible agregar evidencia.'); } finally { setSaving(false); } };
    return <div className="space-y-4"><div className="flex justify-between gap-3"><div><h3 className="font-bold text-slate-800">Evidencias y POD</h3><p className="text-xs text-slate-400">Referencias y enlaces; no se simulan uploads. POD se administra en Documentos.</p></div>{canManage && <button onClick={() => setFormOpen((value) => !value)} className="inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-xs font-bold text-white"><Plus size={14} />Agregar</button>}</div>
        {formOpen && <form onSubmit={submit} className="grid gap-3 rounded-2xl border border-slate-200 bg-slate-50 p-4 sm:grid-cols-2"><label className="text-xs font-bold text-slate-500">Tipo<select value={form.kind} onChange={(e) => setForm({ ...form, kind: e.target.value as EvidenceKind })} className="mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm font-normal"><option value="operational_note">Nota operativa</option><option value="file_reference">Referencia de archivo</option><option value="image_link">Enlace de imagen</option><option value="external_link">Enlace externo</option></select></label><label className="text-xs font-bold text-slate-500">Incidencia relacionada<select value={form.incident} onChange={(e) => setForm({ ...form, incident: e.target.value })} className="mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm font-normal"><option value="">Sin incidencia</option>{data.incidents.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label className="text-xs font-bold text-slate-500">Nota<input value={form.note} onChange={(e) => setForm({ ...form, note: e.target.value })} className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm font-normal" /></label><label className="text-xs font-bold text-slate-500">Referencia de archivo<input value={form.reference} onChange={(e) => setForm({ ...form, reference: e.target.value })} className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm font-normal" /></label><label className="sm:col-span-2 text-xs font-bold text-slate-500">URL<input type="url" value={form.url} onChange={(e) => setForm({ ...form, url: e.target.value })} className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm font-normal" /></label>{error && <p className="sm:col-span-2 rounded-lg bg-red-50 p-3 text-xs text-red-700">{error}</p>}<div className="sm:col-span-2 flex justify-end"><button disabled={saving} className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-xs font-bold text-white">{saving && <Loader2 size={14} className="animate-spin" />}Guardar evidencia</button></div></form>}
        <div className="space-y-2">{data.evidence.map((item) => <article key={item.id} className="rounded-xl border border-slate-200 p-3"><div className="flex gap-3"><FileText size={16} className="mt-0.5 text-primary" /><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><p className="text-xs font-bold text-slate-700">{item.kind.replaceAll('_', ' ')}</p><span className="text-[11px] text-slate-400">{formatOperationDate(item.created_at)}</span></div><p className="mt-1 text-xs text-slate-500">{item.note || item.file_ref || 'Referencia externa'}</p>{item.incident_title && <p className="mt-1 text-[11px] text-amber-700">Incidencia: {item.incident_title}</p>}{item.external_url && <a href={item.external_url} target="_blank" rel="noreferrer" className="mt-2 inline-flex items-center gap-1 text-xs font-bold text-primary">Abrir enlace <ExternalLink size={12} /></a>}</div></div></article>)}{!data.evidence.length && <p className="rounded-xl border border-dashed border-slate-300 p-8 text-center text-sm text-slate-400">Sin evidencia registrada.</p>}</div>
    </div>;
}
