import { useState, type FormEvent } from 'react';
import { Loader2, MapPinned, PencilLine, Plus, Trash2 } from 'lucide-react';
import { deleteOperationCrossing, upsertOperationCrossing } from '@/services/operations.service';
import type { CrossingType, Operation360Data, OperationCrossing } from '@/types/operations';
import { formatOperationDate } from './operationsControl';

const localDate = (value?: string) => value ? new Date(new Date(value).getTime() - new Date(value).getTimezoneOffset() * 60000).toISOString().slice(0, 16) : new Date(Date.now() - new Date().getTimezoneOffset() * 60000).toISOString().slice(0, 16);
export function OperationCrossings({ data, canManage, onRefresh }: { data: Operation360Data; canManage: boolean; onRefresh: () => Promise<void> }) {
    const [editing, setEditing] = useState<OperationCrossing | null>(null); const [formOpen, setFormOpen] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
    const [form, setForm] = useState({ at: localDate(), point: '', type: 'other' as CrossingType, note: '' });
    if (data.operation.operation_scope !== 'international') return <div className="rounded-2xl border border-dashed border-slate-300 p-10 text-center text-sm text-slate-400"><MapPinned className="mx-auto mb-2" />Cruces se habilita solo para operaciones internacionales.</div>;
    const start = (item?: OperationCrossing) => { setEditing(item || null); setForm({ at: localDate(item?.crossed_at), point: item?.crossing_point || '', type: item?.crossing_type || 'other', note: item?.note || '' }); setFormOpen(true); };
    const submit = async (event: FormEvent) => { event.preventDefault(); if (!data.operation.db_id) return; setSaving(true); setError(null); try { await upsertOperationCrossing(data.operation.db_id, { id: editing?.id, crossed_at: new Date(form.at).toISOString(), crossing_point: form.point, crossing_type: form.type, note: form.note }); setFormOpen(false); setEditing(null); await onRefresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No fue posible guardar el cruce.'); } finally { setSaving(false); } };
    const remove = async (id: string) => { if (!window.confirm('¿Eliminar este cruce?')) return; setSaving(true); try { await deleteOperationCrossing(id); await onRefresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No fue posible eliminar el cruce.'); } finally { setSaving(false); } };
    return <div className="space-y-4"><div className="flex justify-between gap-3"><div><h3 className="font-bold text-slate-800">Cruces internacionales</h3><p className="text-xs text-slate-400">Entradas, salidas y otros cruces registrados.</p></div>{canManage && <button onClick={() => start()} className="inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-xs font-bold text-white"><Plus size={14} />Agregar cruce</button>}</div>
        {formOpen && <form onSubmit={submit} className="grid gap-3 rounded-2xl border border-slate-200 bg-slate-50 p-4 sm:grid-cols-2"><label className="text-xs font-bold text-slate-500">Fecha/hora<input required type="datetime-local" value={form.at} onChange={(e) => setForm({ ...form, at: e.target.value })} className="mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm font-normal" /></label><label className="text-xs font-bold text-slate-500">Tipo<select value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value as CrossingType })} className="mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm font-normal"><option value="entry">Entrada</option><option value="exit">Salida</option><option value="other">Otro</option></select></label><label className="text-xs font-bold text-slate-500">Punto de cruce<input required value={form.point} onChange={(e) => setForm({ ...form, point: e.target.value })} className="mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm font-normal" /></label><label className="text-xs font-bold text-slate-500">Nota<input value={form.note} onChange={(e) => setForm({ ...form, note: e.target.value })} className="mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm font-normal" /></label>{error && <p className="sm:col-span-2 rounded-lg bg-red-50 p-3 text-xs text-red-700">{error}</p>}<div className="sm:col-span-2 flex justify-end"><button disabled={saving} className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-xs font-bold text-white">{saving && <Loader2 size={14} className="animate-spin" />}{editing ? 'Guardar cambios' : 'Registrar cruce'}</button></div></form>}
        <div className="space-y-2">{data.crossings.map((item) => <article key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 p-4"><div><p className="text-sm font-bold text-slate-700">{item.crossing_point}</p><p className="mt-1 text-xs text-slate-500">{item.crossing_type === 'entry' ? 'Entrada' : item.crossing_type === 'exit' ? 'Salida' : 'Otro'} · {formatOperationDate(item.crossed_at)}{item.note ? ` · ${item.note}` : ''}</p></div>{canManage && <div className="flex gap-2"><button onClick={() => start(item)} className="rounded-lg bg-slate-100 p-2 text-slate-600"><PencilLine size={14} /></button><button onClick={() => void remove(item.id)} className="rounded-lg bg-red-50 p-2 text-red-600"><Trash2 size={14} /></button></div>}</article>)}{!data.crossings.length && <p className="rounded-xl border border-dashed border-slate-300 p-8 text-center text-sm text-slate-400">Sin cruces registrados.</p>}</div>
    </div>;
}
