import { useMemo, useState, type FormEvent } from 'react';
import { AlertTriangle, CheckCircle2, Loader2, Plus, XCircle } from 'lucide-react';
import { createOperationIncident, dismissOperationIncident, resolveOperationIncident } from '@/services/operations.service';
import type { IncidentCategory, IncidentStatus, Operation360Data } from '@/types/operations';
import { formatOperationDate } from './operationsControl';

const CATEGORY_LABELS: Record<IncidentCategory, string> = { delay: 'Demora', loading_unloading: 'Carga/descarga', vehicle_issue: 'Unidad', driver_issue: 'Chofer', documents_issue: 'Documentos', general: 'General' };
export function OperationIncidents({ data, canManage, onRefresh }: { data: Operation360Data; canManage: boolean; onRefresh: () => Promise<void> }) {
    const [filter, setFilter] = useState<IncidentStatus | 'all'>('open');
    const [formOpen, setFormOpen] = useState(false);
    const [saving, setSaving] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [form, setForm] = useState({ category: 'general' as IncidentCategory, title: '', description: '', blocking: false });
    const items = useMemo(() => filter === 'all' ? data.incidents : data.incidents.filter((item) => item.status === filter), [data.incidents, filter]);
    const submit = async (event: FormEvent) => { event.preventDefault(); if (!data.operation.db_id) return; setSaving(true); setError(null); try { await createOperationIncident(data.operation.db_id, { category: form.category, title: form.title, description: form.description, is_blocking: form.blocking }); setForm({ category: 'general', title: '', description: '', blocking: false }); setFormOpen(false); await onRefresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No fue posible registrar la incidencia.'); } finally { setSaving(false); } };
    const action = async (kind: 'resolve' | 'dismiss', id: string) => { const note = window.prompt(kind === 'resolve' ? 'Nota de resolución:' : 'Motivo para descartar:') ?? ''; setSaving(true); setError(null); try { if (kind === 'resolve') await resolveOperationIncident(id, note); else await dismissOperationIncident(id, note); await onRefresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No fue posible actualizar la incidencia.'); } finally { setSaving(false); } };
    return <div className="space-y-4">
        <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex gap-2">{(['open','resolved','dismissed','all'] as const).map((value) => <button key={value} onClick={() => setFilter(value)} className={`rounded-lg px-3 py-2 text-xs font-bold ${filter === value ? 'bg-slate-800 text-white' : 'bg-slate-100 text-slate-500'}`}>{value === 'open' ? 'Abiertas' : value === 'resolved' ? 'Resueltas' : value === 'dismissed' ? 'Descartadas' : 'Todas'}</button>)}</div>{canManage && <button onClick={() => setFormOpen((value) => !value)} className="inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-xs font-bold text-white"><Plus size={14} />Nueva incidencia</button>}</div>
        {formOpen && <form onSubmit={submit} className="grid gap-3 rounded-2xl border border-slate-200 bg-slate-50 p-4 sm:grid-cols-2"><label className="text-xs font-bold text-slate-500">Categoría<select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value as IncidentCategory })} className="mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm font-normal">{Object.entries(CATEGORY_LABELS).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="text-xs font-bold text-slate-500">Título<input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm font-normal" /></label><label className="sm:col-span-2 text-xs font-bold text-slate-500">Detalle<textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm font-normal" /></label><label className="flex items-center gap-2 text-xs font-bold text-red-700"><input type="checkbox" checked={form.blocking} onChange={(e) => setForm({ ...form, blocking: e.target.checked })} />Bloquea despacho/cierre</label><div className="flex justify-end"><button disabled={saving} className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-xs font-bold text-white">{saving && <Loader2 size={14} className="animate-spin" />}Guardar</button></div></form>}
        {error && <p className="rounded-xl bg-red-50 p-3 text-xs font-semibold text-red-700">{error}</p>}
        <div className="space-y-3">{items.map((item) => <article key={item.id} className={`rounded-2xl border p-4 ${item.status === 'open' && item.is_blocking ? 'border-red-300 bg-red-50' : 'border-slate-200'}`}><div className="flex flex-wrap justify-between gap-3"><div><div className="flex items-center gap-2">{item.is_blocking && <AlertTriangle size={15} className="text-red-600" />}<h3 className="font-bold text-slate-800">{item.title}</h3><span className="rounded-full bg-white px-2 py-0.5 text-[10px] font-bold uppercase text-slate-500">{CATEGORY_LABELS[item.category]}</span></div><p className="mt-1 text-xs text-slate-500">{item.description || 'Sin detalle'} · {formatOperationDate(item.reported_at)}</p>{item.resolution_note && <p className="mt-2 text-xs text-emerald-700">Resolución: {item.resolution_note}</p>}{item.dismiss_note && <p className="mt-2 text-xs text-slate-500">Descarte: {item.dismiss_note}</p>}</div>{canManage && item.status === 'open' && <div className="flex gap-2"><button disabled={saving} onClick={() => void action('resolve', item.id)} className="inline-flex items-center gap-1 rounded-lg bg-emerald-100 px-3 py-2 text-xs font-bold text-emerald-700"><CheckCircle2 size={14} />Resolver</button><button disabled={saving} onClick={() => void action('dismiss', item.id)} className="inline-flex items-center gap-1 rounded-lg bg-slate-100 px-3 py-2 text-xs font-bold text-slate-600"><XCircle size={14} />Descartar</button></div>}</div></article>)}{items.length === 0 && <p className="rounded-xl border border-dashed border-slate-300 p-8 text-center text-sm text-slate-400">Sin incidencias en este filtro.</p>}</div>
    </div>;
}
