import { useEffect, useState, type FormEvent } from 'react';
import { CheckCircle2, ExternalLink, FileWarning, Loader2, PencilLine } from 'lucide-react';
import { upsertOperationDocument } from '@/services/operations.service';
import type { DocumentRequirementLevel, Operation360Data, OperationDocument, OperationDocumentStatus } from '@/types/operations';
import { formatOperationDate } from './operationsControl';

function DocumentEditor({ document, canManage, onRefresh }: { key?: string; document: OperationDocument; canManage: boolean; onRefresh: () => Promise<void> }) {
    const [editing, setEditing] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
    const [form, setForm] = useState({ requirement: document.requirement_level, status: document.status, reference: document.document_reference || '', file: document.file_ref || '', url: document.external_url || '', note: document.note || '' });
    useEffect(() => setForm({ requirement: document.requirement_level, status: document.status, reference: document.document_reference || '', file: document.file_ref || '', url: document.external_url || '', note: document.note || '' }), [document]);
    const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(null); try { await upsertOperationDocument(document.operation_id, { document_type: document.document_type, requirement_level: form.requirement, status: form.status, document_reference: form.reference, file_ref: form.file, external_url: form.url, note: form.note }); await onRefresh(); setEditing(false); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No fue posible guardar el documento.'); } finally { setSaving(false); } };
    const missing = document.requirement_level === 'required' && document.status === 'missing';
    return <article className={`rounded-2xl border p-4 ${missing ? 'border-red-200 bg-red-50/60' : document.status === 'present' ? 'border-emerald-200 bg-emerald-50/40' : 'border-slate-200'}`}><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex gap-2">{document.status === 'present' ? <CheckCircle2 size={17} className="mt-0.5 text-emerald-600" /> : <FileWarning size={17} className={missing ? 'mt-0.5 text-red-600' : 'mt-0.5 text-slate-400'} />}<div><h3 className="text-sm font-bold text-slate-800">{document.display_label}</h3><p className="mt-1 text-xs text-slate-500">{document.requirement_level === 'required' ? 'Requerido' : document.requirement_level === 'not_required' ? 'No requerido' : 'Opcional'} · {document.status === 'present' ? 'Presente' : 'Faltante'}</p>{document.updated_at && <p className="mt-1 text-[11px] text-slate-400">Actualizado {formatOperationDate(document.updated_at)}</p>}</div></div>{canManage && <button onClick={() => setEditing((value) => !value)} className="inline-flex items-center gap-1 rounded-lg bg-white px-3 py-2 text-xs font-bold text-slate-600 ring-1 ring-slate-200"><PencilLine size={13} />Editar</button>}</div>
        {!editing && <div className="mt-3 grid gap-2 text-xs text-slate-600 sm:grid-cols-2"><p>Referencia: <b>{document.document_reference || document.file_ref || 'Datos por confirmar'}</b></p><p>Nota: <b>{document.note || 'Sin nota'}</b></p>{document.external_url && <a className="inline-flex items-center gap-1 font-bold text-primary" href={document.external_url} target="_blank" rel="noreferrer">Abrir documento <ExternalLink size={12} /></a>}</div>}
        {editing && <form onSubmit={submit} className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold text-slate-500">Requisito<select value={form.requirement} onChange={(e) => setForm({ ...form, requirement: e.target.value as DocumentRequirementLevel })} className="mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm font-normal"><option value="required">Requerido</option><option value="optional">Opcional</option><option value="not_required">No requerido</option></select></label><label className="text-xs font-bold text-slate-500">Estado<select value={form.status} disabled={form.requirement === 'not_required'} onChange={(e) => setForm({ ...form, status: e.target.value as OperationDocumentStatus })} className="mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm font-normal"><option value="missing">Faltante</option><option value="present">Presente</option></select></label>{[['Referencia','reference'],['Archivo/ref. storage','file'],['URL','url'],['Nota','note']].map(([label,key]) => <label key={key} className="text-xs font-bold text-slate-500">{label}<input type={key === 'url' ? 'url' : 'text'} value={form[key as keyof typeof form]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} className="mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm font-normal" /></label>)}{error && <p className="sm:col-span-2 rounded-lg bg-red-50 p-3 text-xs text-red-700">{error}</p>}<div className="sm:col-span-2 flex justify-end"><button disabled={saving} className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-xs font-bold text-white">{saving && <Loader2 size={14} className="animate-spin" />}Guardar</button></div></form>}
    </article>;
}

export function OperationDocuments({ data, canManage, onRefresh }: { data: Operation360Data; canManage: boolean; onRefresh: () => Promise<void> }) {
    return <div className="space-y-4"><div className={`rounded-2xl border p-4 ${data.documentSummary.pod_present ? 'border-emerald-200 bg-emerald-50' : 'border-amber-200 bg-amber-50'}`}><p className="text-sm font-bold text-slate-800">POD: {data.documentSummary.pod_present ? 'Presente' : 'Pendiente'}</p><p className="mt-1 text-xs text-slate-500">La prueba de entrega permanece como documento canónico `proof_of_delivery`; no se creó tabla POD.</p></div><div className="grid gap-3 lg:grid-cols-2">{data.documents.map((document) => <DocumentEditor key={document.document_type} document={document} canManage={canManage} onRefresh={onRefresh} />)}</div><div className="rounded-xl border border-dashed border-slate-300 p-4 text-xs text-slate-500">Upload futuro: la UI conserva `file_ref` como punto de integración con `document_files`; F2 no simula carga ni agrega storage.</div></div>;
}
