-- History marker only (DB.0B). The original remote SQL was not recovered.
-- Approved effects for this version are represented in 20260223000000_canonical_baseline.sql.
-- This file is intentionally a no-op and does not claim to reproduce the original body.
