import { ArrowUpRight, History } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import type { RecentActivityItem } from '@/types/executive';

export function RecentActivity({ items }: { items: RecentActivityItem[] }) {
    const navigate=useNavigate();
    const moduleLabel=(module:string)=>({operations:'Operaciones',commercial:'Comercial',finance:'Finanzas',billing:'Facturación',documents:'Documentos',claims:'Reclamaciones'} as Record<string,string>)[module.toLowerCase()]??'Actividad';
    return <section className="min-w-0 max-w-full overflow-hidden rounded-2xl border bg-surface-card"><header className="min-w-0 border-b px-4 py-4 sm:px-5"><h2 className="flex min-w-0 items-center gap-2 font-black text-slate-800"><History size={17} className="shrink-0"/>Actividad reciente</h2><p className="text-xs leading-relaxed text-slate-400">Eventos de negocio normalizados.</p></header><div className="min-w-0 divide-y">{items.length===0?<p className="p-8 text-center text-sm text-slate-400">Sin actividad en el periodo.</p>:items.slice(0,12).map((item)=><button key={item.id} onClick={()=>navigate(item.route)} className="flex w-full min-w-0 items-start gap-2.5 px-3 py-3 text-left active:bg-semantic-neutral-soft sm:items-center sm:gap-3 sm:px-5 sm:hover:bg-semantic-neutral-soft"><span className="mt-1.5 h-2 w-2 shrink-0 rounded-full bg-primary sm:mt-0"/><span className="min-w-0 flex-1"><b className="block break-words text-xs text-slate-700">{item.title}</b><span className="mt-0.5 block break-words text-[11px] leading-relaxed text-slate-400">{item.subtitle} · {new Date(item.occurred_at).toLocaleString('es-MX')}</span></span><span className="max-w-[35%] shrink-0 truncate rounded-full bg-semantic-neutral-soft px-2 py-1 text-[9px] font-bold uppercase text-semantic-neutral">{moduleLabel(item.module)}</span><ArrowUpRight size={13} className="shrink-0 text-slate-300"/></button>)}</div></section>;
}
